import type { GraphNode, GraphLink } from './graph'
export type AttackPathType='PRIVILEGE_REACHABILITY'|'DOMAIN_ADMIN'|'TIER_ZERO'|'SUDO_ROOT'|'PRODUCTION_HOST'|'FINANCE_APPLICATION'|'CRITICAL_DATABASE'|'BUSINESS_SERVICE'|'CROSS_DOMAIN'|'LATERAL_MOVEMENT'|'IDENTITY_TO_APPLICATION'|'APPLICATION_TO_DATABASE'|'PRIVILEGE_ESCALATION'
export type PathAlgorithm='shortest'|'weighted'|'all'
export interface AttackPath { id:string;type:AttackPathType;sourceNode:GraphNode;targetNode:GraphNode;nodes:GraphNode[];relationships:GraphLink[];totalDepth:number;totalWeight:number;totalRiskScore:number;factorScores:{factor:string;score:number;reason:string}[];severity:string;sourceSystems:string[];accessMode:'DIRECT'|'INHERITED';privilegedTargetType:AttackPathType;explanation:string;confidence:string;evidence:{relationshipId:string;relationshipType:string;classification:string;sourceSystem:string;why:string;riskContribution:number}[];mitigations:string[];createdAt:string }
export interface AttackSearch { sourceNodeId?:string;targetNodeId?:string;targetType?:AttackPathType;maxDepth:number;maxPaths:number;directed:boolean;algorithm?:PathAlgorithm;minimumRiskScore?:number }
export interface AttackSummary { totalPaths:number;criticalPaths:number;highRiskPaths:number;uniqueSourceIdentities:number;uniquePrivilegedTargets:number;pathsByType:Record<string,number>;topSourceIdentities:{id:string;count:number}[];topPrivilegedTargets:{id:string;count:number}[];latestAnalysisTime?:string;durationMs:number }
export interface AttackPathRun { id:string;status:'RUNNING'|'COMPLETED'|'FAILED';request:Partial<AttackSearch>;pathCount:number;durationMs:number|null;error?:string;startedAt:string;completedAt?:string }
export interface ChokePoint { node:GraphNode;pathCount:number;percentage:number;sourceCount:number;targetCount:number }
export interface BlastRadius { nodeId:string;reachableNodeCount:number;privilegedTargetCount:number;maximumDepth:number;affectedNodes:GraphNode[] }
