import assert from 'node:assert/strict';import{describe,it}from'node:test';import type{GraphData,GraphNode}from'../../types/graph';import{clusterGraph,disconnectedComponentPositions,edgeVisualStyle,filterGraphView,labelVisibility,loadLayout,loadSavedViews,nodeVisualStyle,saveLayout,saveSavedViews,type SavedGraphView}from'../graphPresentation'
const node=(id:string,nodeType:GraphNode['nodeType']='USER',riskLevel:GraphNode['riskLevel']='NONE',properties:Record<string,unknown>={}):GraphNode=>({id,displayName:id,nodeType,sourceSystem:'ACTIVE_DIRECTORY',riskLevel,properties})
const data:GraphData={nodes:[node('critical','USER','CRITICAL',{department:'Security',privileged:true}),node('group','GROUP','NONE',{department:'Security'}),node('host','HOST','LOW',{department:'IT'}),node('isolated','APPLICATION')],links:[{id:'member',source:'critical',target:'group',relationshipType:'MEMBER_OF',sourceSystem:'ACTIVE_DIRECTORY'},{id:'access',source:'group',target:'host',relationshipType:'HAS_ACCESS_TO',sourceSystem:'ACTIVE_DIRECTORY'}]}
describe('enterprise graph presentation',()=>{
  it('filters progressive view modes with adjacent context',()=>{const access=filterGraphView(data,'access');assert.ok(access.nodes.some(n=>n.id==='critical'));assert.ok(access.nodes.some(n=>n.id==='host'));assert.equal(filterGraphView(data,'full'),data)})
  it('clusters without mutating original graph',()=>{const clustered=clusterGraph(data,'department');assert.equal(data.nodes.length,4);assert.ok(clustered.nodes.every(n=>n.properties.isCluster===true));assert.equal(clustered.nodes.find(n=>n.displayName==='Security')?.properties.nodeCount,2)})
  it('shows only priority labels far away',()=>{assert.equal(labelVisibility(node('plain'),.3,{}),false);assert.equal(labelVisibility(node('risk','USER','CRITICAL'),.3,{}),true);assert.equal(labelVisibility(node('plain'),2,{}),true)})
  it('resolves accessible shape and risk badge semantics',()=>{assert.equal(nodeVisualStyle(node('role','ROLE','HIGH')).shape,'shield');assert.equal(nodeVisualStyle(node('db','DATABASE','LOW')).shape,'cylinder');assert.equal(nodeVisualStyle(node('risk','USER','CRITICAL')).riskRing,'pulse-red')})
  it('resolves edge semantics',()=>{assert.equal(edgeVisualStyle(data.links[0],{}).dash,'dashed');assert.equal(edgeVisualStyle(data.links[1],{shortest:true}).color,'cyan')})
  it('organizes disconnected components compactly',()=>{const positions=disconnectedComponentPositions(data);assert.equal(positions.size,4);assert.notDeepEqual(positions.get('critical'),positions.get('isolated'))})
  it('persists layouts and saved views',()=>{const values=new Map<string,string>();const storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)}};saveLayout(storage,'mock','radial');assert.equal(loadLayout(storage,'mock'),'radial');const view:SavedGraphView={id:'1',name:'Security',layout:'force',filters:{systems:[],nodeTypes:[],relationshipTypes:[],riskLevels:[],statuses:[],accessTypes:[],searchQuery:''},source:'mock',expandedNodes:[],clustering:'department',viewMode:'privileged'};saveSavedViews(storage,[view]);assert.deepEqual(loadSavedViews(storage),[view])})
})
