import assert from 'node:assert/strict'; import { describe,it } from 'node:test'; import neo4j from 'neo4j-driver'; import { Neo4jHealthController } from '../neo4j.health'; import { Neo4jService,resolveNeo4jConfig } from '../neo4j.service'; import { Neo4jQueryError,Neo4jUnavailableError } from '../neo4j.types'; import { Neo4jGraphRepository } from '../../graph/repositories/neo4j-graph.repository'; import { ImportGraphPersistenceService } from '../../imports/import-graph-persistence.service'
const config=(values:Record<string,string>={})=>({get:(key:string)=>values[key]}) as any
const record=(values:Record<string,unknown>)=>({get:(key:string)=>values[key]}) as any
function driverMock(run:(_:string,__:unknown)=>Promise<any>){let closed=0;const session={run,close:async()=>{closed++},executeRead:async(fn:any)=>fn({}),executeWrite:async(fn:any)=>fn({})};return{driver:{session:()=>session,close:async()=>undefined,verifyConnectivity:async()=>undefined,getServerInfo:async()=>({agent:'Neo4j/5.test'})} as any,get closed(){return closed}}}
describe('neo4j foundation',()=>{
  it('validates enabled configuration without exposing defaults for credentials',()=>{assert.throws(()=>resolveNeo4jConfig({NEO4J_ENABLED:'true'}),/NEO4J_URI/);const result=resolveNeo4jConfig({NEO4J_ENABLED:'true',NEO4J_URI:'neo4j:\/\/db',NEO4J_USERNAME:'app',NEO4J_PASSWORD:'secret'});assert.equal(result.database,'neo4j');assert.equal(result.password,'secret')})
  it('supports disabled mode without constructing a driver',async()=>{const service=new Neo4jService(config());assert.equal(service.isEnabled(),false);assert.equal(await service.verifyConnectivity(),false);assert.throws(()=>service.connect(),Neo4jUnavailableError)})
  it('returns safe disabled and connected health responses',async()=>{const disabled=await new Neo4jHealthController(new Neo4jService(config())).check();assert.equal(disabled.status,'disabled');assert.equal((disabled as any).password,undefined);const mock=driverMock(async()=>({records:[]}));const enabled=new Neo4jService(config({NEO4J_ENABLED:'true',NEO4J_URI:'neo4j://db',NEO4J_USERNAME:'app',NEO4J_PASSWORD:'secret'}),()=>mock.driver);const health=await new Neo4jHealthController(enabled).check();assert.equal(health.serverAgent,'Neo4j/5.test');assert.equal(health.connectivity,true)})
  it('closes sessions and passes parameters separately',async()=>{let cypher='';let parameters:any;const mock=driverMock(async(q,p)=>{cypher=q;parameters=p;return{records:[]}});const service=new Neo4jService(config({NEO4J_ENABLED:'true',NEO4J_URI:'neo4j://db',NEO4J_USERNAME:'app',NEO4J_PASSWORD:'secret'}),()=>mock.driver);await service.read('MATCH (n {id: $id}) RETURN n',{id:'user-1'});assert.match(cypher,/\$id/);assert.deepEqual(parameters,{id:'user-1'});assert.equal(mock.closed,1)})
  it('maps driver failures and still closes the session',async()=>{const mock=driverMock(async()=>{throw Object.assign(new Error('socket details'),{code:'Neo.TransientError.Network'})});const service=new Neo4jService(config({NEO4J_ENABLED:'true',NEO4J_URI:'neo4j://db',NEO4J_USERNAME:'app',NEO4J_PASSWORD:'secret'}),()=>mock.driver);await assert.rejects(()=>service.write('RETURN $value',{value:1}),(error:any)=>error instanceof Neo4jQueryError&&error.message==='Neo4j operation temporarily unavailable');assert.equal(mock.closed,1)})
  it('generates parameterized MERGE and batch UNWIND node writes',async()=>{const calls:any[]=[];const fake={write:async(q:string,p:any)=>{calls.push([q,p]);return{records:[record({node:p.row?.properties,count:neo4j.int(p.rows?.length??1)})]}}};const repository=new Neo4jGraphRepository(fake as any);await repository.upsertNode({id:'u1',displayName:'User',nodeType:'USER',sourceSystem:'AD'});await repository.upsertNodes([{id:'u1',displayName:'User',nodeType:'USER',sourceSystem:'AD'}]);assert.match(calls[0][0],/MERGE \(n:GraphNode \{id: \$row.id\}\)/);assert.match(calls[1][0],/UNWIND \$rows/);assert.equal(calls[0][1].row.id,'u1')})
  it('generates typed MERGE and batch UNWIND relationship writes',async()=>{const calls:any[]=[];const fake={write:async(q:string,p:any)=>{calls.push([q,p]);return{records:[record({relationship:p.row,count:neo4j.int(p.rows?.length??1)})]}}};const repository=new Neo4jGraphRepository(fake as any);const relationship={id:'r1',source:'u1',target:'g1',relationshipType:'MEMBER_OF',sourceSystem:'AD'};await repository.upsertRelationship(relationship);const summary=await repository.upsertRelationships([relationship]);assert.match(calls[0][0],/\[r:MEMBER_OF/);assert.match(calls[1][0],/UNWIND \$rows/);assert.equal(summary.upserted,1)})
  it('summarizes import preview persistence',async()=>{const imports={getConversionResult:()=>({preview:{nodes:[{id:'u1'}],links:[{id:'r1'}]},conflicts:['review']})};const graph={upsertNodes:async()=>({upserted:1,skipped:0}),upsertRelationships:async()=>({upserted:1,skipped:0})};const summary=await new ImportGraphPersistenceService(imports as any,graph as any).persistConvertedGraph('imp');assert.deepEqual({...summary,durationMs:0},{nodesUpserted:1,relationshipsUpserted:1,skipped:0,conflicts:1,durationMs:0})})
})
