import {
  NodeType, SourceSystem, RiskLevel, AccountStatus, OperatingSystemType,
} from '@identity-access-graph/graph-model'
import type {
  Forest, Domain, OrganizationalUnit, Department, Team, User, Group,
  Role, Permission, Computer, Host, OperatingSystem, Site, Subnet,
  LinuxUser, LinuxGroup, SudoPolicy, SSHKey, Application, Database,
  BusinessService, ServiceAccount, ManagedServiceAccount, GroupPolicy,
  Manager,
} from '@identity-access-graph/graph-model'

const TS = '2024-01-01T00:00:00Z'

function n<T>(partial: T & { id: string; displayName: string }): T {
  return partial
}

// ── Forest ─────────────────────────────────────────────────────
export const forest: Forest = n({
  id: 'forest-nexus', displayName: 'NexusCore Forest', description: 'Corporate AD forest for NexusCore Industries',
  nodeType: NodeType.Forest, sourceSystem: SourceSystem.ActiveDirectory, rootDomain: 'nexuscore.com',
  domainIds: ['dom-nexus'], forestMode: 'Windows 2016', schemaVersion: '87',
  metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
  enabled: true, deleted: false, critical: true,
})

// ── Domain ──────────────────────────────────────────────────────
export const domain: Domain = n({
  id: 'dom-nexus', displayName: 'nexuscore.com', description: 'Primary corporate Active Directory domain',
  nodeType: NodeType.Domain, sourceSystem: SourceSystem.ActiveDirectory,
  dnsName: 'nexuscore.com', netBiosName: 'NEXUSCORP', forestId: 'forest-nexus',
  domainFunctionLevel: '2016', sid: 'S-1-5-21-3623811015-3361044348-30300820',
  controllerIds: ['computer-dc-01'],
  metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
  enabled: true, deleted: false, critical: true,
})

// ── Organizational Units ────────────────────────────────────────
export const organizationalUnits: OrganizationalUnit[] = [
  n({ id: 'ou-users', displayName: 'Users', description: 'Default user container', path: 'CN=Users,DC=nexuscore,DC=com',
    distinguishedName: 'CN=Users,DC=nexuscore,DC=com', domainId: 'dom-nexus', protected: false,
    nodeType: NodeType.OrganizationalUnit, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.None,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'ou-computers', displayName: 'Computers', description: 'Default computer container', path: 'CN=Computers,DC=nexuscore,DC=com',
    distinguishedName: 'CN=Computers,DC=nexuscore,DC=com', domainId: 'dom-nexus', protected: false,
    nodeType: NodeType.OrganizationalUnit, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'ou-servers', displayName: 'Servers', description: 'Server computer objects', path: 'OU=Servers,DC=nexuscore,DC=com',
    distinguishedName: 'OU=Servers,DC=nexuscore,DC=com', domainId: 'dom-nexus', protected: true, gpoIds: ['gpo-security-baseline', 'gpo-windows-update'],
    nodeType: NodeType.OrganizationalUnit, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'ou-service-accounts', displayName: 'Service Accounts', description: 'Managed service accounts container', path: 'OU=Service Accounts,DC=nexuscore,DC=com',
    distinguishedName: 'OU=Service Accounts,DC=nexuscore,DC=com', domainId: 'dom-nexus', protected: false,
    nodeType: NodeType.OrganizationalUnit, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
]

// ── Departments ─────────────────────────────────────────────────
export const departments: Department[] = [
  n({ id: 'dept-it', displayName: 'Information Technology', description: 'Core IT infrastructure and application services', code: 'IT',
    nodeType: NodeType.Department, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'dept-infosec', displayName: 'Information Security', description: 'Security operations, IAM, and compliance', code: 'SEC',
    nodeType: NodeType.Department, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'dept-fin', displayName: 'Finance', description: 'Financial operations and accounting', code: 'FIN',
    nodeType: NodeType.Department, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'dept-hr', displayName: 'Human Resources', description: 'Workforce management and talent acquisition', code: 'HR',
    nodeType: NodeType.Department, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
]

// ── Teams ───────────────────────────────────────────────────────
export const teams: Team[] = [
  n({ id: 'team-iam', displayName: 'Identity & Access Management', description: 'IAM operations and directory services',
    departmentId: 'dept-infosec', purpose: 'Manage identity lifecycle, SSO, and access governance',
    nodeType: NodeType.Team, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'team-soc', displayName: 'Security Operations Center', description: '24/7 monitoring and incident response',
    departmentId: 'dept-infosec', purpose: 'Monitor, detect, and respond to security incidents',
    nodeType: NodeType.Team, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'team-infra', displayName: 'Infrastructure', description: 'Server, network, and cloud infrastructure',
    departmentId: 'dept-it', purpose: 'Maintain core infrastructure and platform services',
    nodeType: NodeType.Team, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'team-app-support', displayName: 'Application Support', description: 'Application maintenance and user support',
    departmentId: 'dept-it', purpose: 'Support enterprise applications and resolve incidents',
    nodeType: NodeType.Team, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'team-finops', displayName: 'Finance Operations', description: 'Financial system operations and reporting',
    departmentId: 'dept-fin', purpose: 'Manage financial systems and payment processing',
    nodeType: NodeType.Team, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'team-hrops', displayName: 'HR Operations', description: 'HR system administration and payroll',
    departmentId: 'dept-hr', purpose: 'Administer HR systems and employee lifecycle',
    nodeType: NodeType.Team, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
]

// ── Managers ────────────────────────────────────────────────────
export const managers: Manager[] = [
  n({ id: 'mgr-001', displayName: 'Sarah Chen', description: 'Chief Information Officer',
    employeeId: 'EMP-001', title: 'CIO',
    nodeType: NodeType.Manager, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'mgr-009', displayName: 'Kevin Patel', description: 'Engineering Manager',
    employeeId: 'EMP-009', title: 'Engineering Manager',
    nodeType: NodeType.Manager, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'mgr-012', displayName: 'Jennifer Taylor', description: 'HR Director',
    employeeId: 'EMP-012', title: 'HR Director',
    nodeType: NodeType.Manager, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Users ───────────────────────────────────────────────────────
export const users: User[] = [
  n({ id: 'user-001', displayName: 'Sarah Chen', email: 'sarah.chen@nexuscore.com',
    firstName: 'Sarah', lastName: 'Chen', principalName: 'schen@NEXUSCORP', samAccountName: 'schen',
    jobTitle: 'Chief Information Officer', officeLocation: 'New York', mfaEnabled: true,
    departmentId: 'dept-it', teams: ['team-infra'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'user-002', displayName: 'James Wilson', email: 'james.wilson@nexuscore.com',
    firstName: 'James', lastName: 'Wilson', principalName: 'jwilson@NEXUSCORP', samAccountName: 'jwilson',
    jobTitle: 'IAM Engineer', officeLocation: 'New York', mfaEnabled: true,
    departmentId: 'dept-infosec', teams: ['team-iam'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-003', displayName: 'Maria Santos', email: 'maria.santos@nexuscore.com',
    firstName: 'Maria', lastName: 'Santos', principalName: 'msantos@NEXUSCORP', samAccountName: 'msantos',
    jobTitle: 'SOC Analyst', officeLocation: 'New York', mfaEnabled: true,
    departmentId: 'dept-infosec', teams: ['team-soc'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-004', displayName: 'Alex Thompson', email: 'alex.thompson@nexuscore.com',
    firstName: 'Alex', lastName: 'Thompson', principalName: 'athompson@NEXUSCORP', samAccountName: 'athompson',
    jobTitle: 'Infrastructure Engineer', officeLocation: 'San Francisco', mfaEnabled: true,
    departmentId: 'dept-it', teams: ['team-infra'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-005', displayName: 'Emily Davis', email: 'emily.davis@nexuscore.com',
    firstName: 'Emily', lastName: 'Davis', principalName: 'edavis@NEXUSCORP', samAccountName: 'edavis',
    jobTitle: 'Application Support Lead', officeLocation: 'London', mfaEnabled: true,
    departmentId: 'dept-it', teams: ['team-app-support'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-006', displayName: 'Robert Kim', email: 'robert.kim@nexuscore.com',
    firstName: 'Robert', lastName: 'Kim', principalName: 'rkim@NEXUSCORP', samAccountName: 'rkim',
    jobTitle: 'FinOps Analyst', officeLocation: 'London',
    departmentId: 'dept-fin', teams: ['team-finops'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Disabled, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-007', displayName: 'David Miller', email: 'david.miller@nexuscore.com',
    firstName: 'David', lastName: 'Miller', principalName: 'dmiller@NEXUSCORP', samAccountName: 'dmiller',
    jobTitle: 'Linux Administrator', officeLocation: 'San Francisco', mfaEnabled: true,
    departmentId: 'dept-it', teams: ['team-infra'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory, sourceId: 'ad-dmiller',
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-008', displayName: 'Lisa Anderson', email: 'lisa.anderson@nexuscore.com',
    firstName: 'Lisa', lastName: 'Anderson', principalName: 'landerson@NEXUSCORP', samAccountName: 'landerson',
    jobTitle: 'Security Engineer', officeLocation: 'San Francisco', mfaEnabled: true,
    departmentId: 'dept-infosec', teams: ['team-iam'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory, sourceId: 'ad-landerson',
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-009', displayName: 'Kevin Patel', email: 'kevin.patel@nexuscore.io',
    firstName: 'Kevin', lastName: 'Patel', principalName: 'kpatel@LINUX.NEXUSCORE.IO',
    jobTitle: 'DevOps Engineer', officeLocation: 'Singapore', mfaEnabled: true,
    departmentId: 'dept-it', teams: ['team-infra'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.FreeIPA,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-010', displayName: 'Rachel Green', email: 'rachel.green@nexuscore.io',
    firstName: 'Rachel', lastName: 'Green', principalName: 'rgreen@LINUX.NEXUSCORE.IO',
    jobTitle: 'Database Administrator', officeLocation: 'Frankfurt',
    departmentId: 'dept-it', teams: ['team-app-support'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.FreeIPA,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-011', displayName: 'Michael Brown', email: 'michael.brown@nexuscore.com',
    firstName: 'Michael', lastName: 'Brown', principalName: 'mbrown@NEXUSCORP', samAccountName: 'mbrown',
    jobTitle: 'HR Operations Specialist', officeLocation: 'Sydney',
    departmentId: 'dept-hr', teams: ['team-hrops'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'user-012', displayName: 'Jennifer Taylor', email: 'jennifer.taylor@nexuscore.com',
    firstName: 'Jennifer', lastName: 'Taylor', principalName: 'jtaylor@NEXUSCORP', samAccountName: 'jtaylor',
    jobTitle: 'Finance Director', officeLocation: 'London', mfaEnabled: true,
    departmentId: 'dept-fin', teams: ['team-finops'],
    nodeType: NodeType.User, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Groups ──────────────────────────────────────────────────────
export const groups: Group[] = [
  n({ id: 'group-domain-admins', displayName: 'Domain Admins', distinguishedName: 'CN=Domain Admins,CN=Users,DC=nexuscore,DC=com',
    isSecurityGroup: true, scope: 'Global', memberCount: 2,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'group-enterprise-admins', displayName: 'Enterprise Admins', distinguishedName: 'CN=Enterprise Admins,CN=Users,DC=nexuscore,DC=com',
    isSecurityGroup: true, scope: 'Universal', memberCount: 1,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'group-it-staff', displayName: 'IT Staff', distinguishedName: 'CN=IT Staff,CN=Users,DC=nexuscore,DC=com',
    isSecurityGroup: true, scope: 'Global', memberCount: 6,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'group-infosec-team', displayName: 'InfoSec Team', distinguishedName: 'CN=InfoSec Team,CN=Users,DC=nexuscore,DC=com',
    isSecurityGroup: true, scope: 'Global', memberCount: 3,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'group-finance-users', displayName: 'Finance Users', distinguishedName: 'CN=Finance Users,CN=Users,DC=nexuscore,DC=com',
    isSecurityGroup: true, scope: 'Global', memberCount: 2,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'group-hr-users', displayName: 'HR Users', distinguishedName: 'CN=HR Users,CN=Users,DC=nexuscore,DC=com',
    isSecurityGroup: true, scope: 'Global', memberCount: 2,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'group-vpn-access', displayName: 'VPN Access', distinguishedName: 'CN=VPN Access,CN=Users,DC=nexuscore,DC=com',
    isSecurityGroup: true, scope: 'Global', memberCount: 2,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'group-app-prod-access', displayName: 'Production App Access', distinguishedName: 'CN=Production App Access,CN=Users,DC=nexuscore,DC=com',
    isSecurityGroup: true, scope: 'Global', memberCount: 4,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'group-ipa-admins', displayName: 'FreeIPA Admins',
    isSecurityGroup: true,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.FreeIPA,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'group-ipa-users', displayName: 'FreeIPA Users',
    isSecurityGroup: true, memberCount: 0,
    nodeType: NodeType.Group, sourceSystem: SourceSystem.FreeIPA,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Roles ───────────────────────────────────────────────────────
export const roles: Role[] = [
  n({ id: 'role-admin', displayName: 'Administrator', permissionIds: ['perm-app-portal-admin', 'perm-app-idp-admin', 'perm-serv-prod-access'],
    inheritable: true, priority: 1, assignmentType: 'Direct',
    nodeType: NodeType.Role, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'role-auditor', displayName: 'Auditor', permissionIds: ['perm-app-portal-read', 'perm-app-payments-read'],
    inheritable: false, priority: 4, assignmentType: 'Direct',
    nodeType: NodeType.Role, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'role-developer', displayName: 'Developer', permissionIds: ['perm-app-portal-write', 'perm-app-payments-write', 'perm-app-crm-read'],
    inheritable: true, priority: 3, assignmentType: 'Direct',
    nodeType: NodeType.Role, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'role-support', displayName: 'Support Technician', permissionIds: ['perm-app-portal-read'],
    inheritable: false, priority: 5, assignmentType: 'Direct',
    nodeType: NodeType.Role, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'role-finance-analyst', displayName: 'Finance Analyst', permissionIds: ['perm-app-payments-read', 'perm-app-crm-read'],
    inheritable: false, priority: 4, assignmentType: 'Direct',
    nodeType: NodeType.Role, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'role-hr-coordinator', displayName: 'HR Coordinator', permissionIds: ['perm-app-portal-read'],
    inheritable: false, priority: 5, assignmentType: 'Direct',
    nodeType: NodeType.Role, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Permissions ─────────────────────────────────────────────────
export const permissions: Permission[] = [
  n({ id: 'perm-app-portal-read', displayName: 'Read Employee Portal', resource: 'app-employee-portal', action: 'read', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'perm-app-portal-write', displayName: 'Write Employee Portal', resource: 'app-employee-portal', action: 'write', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'perm-app-portal-admin', displayName: 'Admin Employee Portal', resource: 'app-employee-portal', action: 'admin', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'perm-app-payments-read', displayName: 'Read Payment Gateway', resource: 'app-payment-gateway', action: 'read', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'perm-app-payments-write', displayName: 'Write Payment Gateway', resource: 'app-payment-gateway', action: 'write', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'perm-app-crm-read', displayName: 'Read CRM', resource: 'app-crm', action: 'read', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'perm-app-crm-write', displayName: 'Write CRM', resource: 'app-crm', action: 'write', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'perm-app-idp-read', displayName: 'Read Identity Provider', resource: 'app-idp', action: 'read', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'perm-app-idp-admin', displayName: 'Admin Identity Provider', resource: 'app-idp', action: 'admin', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'perm-serv-prod-access', displayName: 'Production Server Access', resource: 'host-web-prod', action: 'login', effect: 'Allow',
    nodeType: NodeType.Permission, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
]

// ── Computers ───────────────────────────────────────────────────
export const computers: Computer[] = [
  n({ id: 'computer-dc-01', displayName: 'NEXDC01', hostname: 'NEXDC01', fqdn: 'dc01.nexuscore.com', ipAddress: '10.0.0.10',
    domainId: 'dom-nexus', operatingSystemId: 'os-win2019', siteId: 'site-nyc', organizationalUnitId: 'ou-servers',
    osVersion: 'Windows Server 2019 Standard', serialNumber: 'VMX-1234-ABCD', dnsHostName: 'dc01.nexuscore.com',
    nodeType: NodeType.Computer, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'computer-web-01', displayName: 'NEXWEB01', hostname: 'NEXWEB01', fqdn: 'web01.nexuscore.com', ipAddress: '10.0.0.20',
    domainId: 'dom-nexus', operatingSystemId: 'os-win2019', siteId: 'site-nyc', organizationalUnitId: 'ou-computers',
    osVersion: 'Windows Server 2019 Standard', serialNumber: 'VMX-1234-EFGH',
    nodeType: NodeType.Computer, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'computer-sql-01', displayName: 'NEXSQL01', hostname: 'NEXSQL01', fqdn: 'sql01.nexuscore.com', ipAddress: '10.0.0.30',
    domainId: 'dom-nexus', operatingSystemId: 'os-win2019', siteId: 'site-nyc', organizationalUnitId: 'ou-servers',
    osVersion: 'Windows Server 2019 Standard', serialNumber: 'VMX-1234-IJKL', serviceAccountIds: ['msvcacct-sql'],
    nodeType: NodeType.Computer, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'computer-file-01', displayName: 'NEXFILE01', hostname: 'NEXFILE01', fqdn: 'file01.nexuscore.com', ipAddress: '10.0.0.40',
    domainId: 'dom-nexus', osVersion: 'Windows Server 2022', siteId: 'site-nyc', organizationalUnitId: 'ou-computers',
    serialNumber: 'VMX-1234-MNOP',
    nodeType: NodeType.Computer, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
]

// ── Hosts ───────────────────────────────────────────────────────
export const hosts: Host[] = [
  n({ id: 'host-web-prod', displayName: 'web-prod.nexuscore.com', hostname: 'web-prod', fqdn: 'web-prod.nexuscore.com',
    ipAddresses: ['10.10.0.10'], operatingSystemId: 'os-win2019', isVirtual: true, hypervisor: 'VMware vSphere', cpuCores: 8, memoryGb: 32, storageGb: 500,
    nodeType: NodeType.Host, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'host-app-prod', displayName: 'app-prod.nexuscore.com', hostname: 'app-prod', fqdn: 'app-prod.nexuscore.com',
    ipAddresses: ['10.10.0.20'], operatingSystemId: 'os-rhel-9', isVirtual: true, hypervisor: 'VMware vSphere', cpuCores: 16, memoryGb: 64, storageGb: 1000,
    nodeType: NodeType.Host, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'host-db-prod', displayName: 'db-prod.nexuscore.com', hostname: 'db-prod', fqdn: 'db-prod.nexuscore.com',
    ipAddresses: ['10.10.0.30'], operatingSystemId: 'os-win2019', isVirtual: true, hypervisor: 'VMware vSphere', cpuCores: 32, memoryGb: 128, storageGb: 5000,
    nodeType: NodeType.Host, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'host-dev-01', displayName: 'dev-01.nexuscore.io', hostname: 'dev-01', fqdn: 'dev-01.nexuscore.io',
    ipAddresses: ['10.30.0.10'], operatingSystemId: 'os-ubuntu-2204', isVirtual: true, hypervisor: 'VMware vSphere', cpuCores: 4, memoryGb: 16, storageGb: 200,
    nodeType: NodeType.Host, sourceSystem: SourceSystem.FreeIPA,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'host-mon-01', displayName: 'mon-01.nexuscore.local', hostname: 'mon-01', fqdn: 'mon-01.nexuscore.local',
    ipAddresses: ['10.0.0.100'], operatingSystemId: 'os-ubuntu-2204', isVirtual: false, cpuCores: 4, memoryGb: 8, storageGb: 500,
    nodeType: NodeType.Host, sourceSystem: SourceSystem.Linux,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Operating Systems ──────────────────────────────────────────
export const operatingSystems: OperatingSystem[] = [
  n({ id: 'os-win2019', displayName: 'Windows Server 2019 Standard', osType: OperatingSystemType.Windows, version: '10.0.17763',
    buildNumber: '17763', patchLevel: 'KB5037768', endOfLife: '2029-01-09', licenseType: 'Datacenter',
    nodeType: NodeType.OperatingSystem, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'os-ubuntu-2204', displayName: 'Ubuntu 22.04 LTS', osType: OperatingSystemType.Linux, version: '22.04.4 LTS (Jammy Jellyfish)',
    kernelVersion: '5.15.0-116-generic', endOfLife: '2027-04-01',
    nodeType: NodeType.OperatingSystem, sourceSystem: SourceSystem.Linux,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'os-rhel-9', displayName: 'Red Hat Enterprise Linux 9', osType: OperatingSystemType.Linux, version: '9.3',
    kernelVersion: '5.14.0-362.8.1.el9_3.x86_64', patchLevel: 'RHEL 9.3', endOfLife: '2032-05-01', licenseType: 'Red Hat Enterprise Linux for Servers',
    nodeType: NodeType.OperatingSystem, sourceSystem: SourceSystem.Linux,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Site & Subnets ──────────────────────────────────────────────
export const site: Site = n({
  id: 'site-nyc', displayName: 'New York Data Center', location: 'New York, NY', siteCode: 'NYC1',
  domainId: 'dom-nexus', description: 'Primary corporate data center',
  nodeType: NodeType.Site, sourceSystem: SourceSystem.ActiveDirectory,
  metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
  enabled: true, deleted: false, critical: true,
})

export const subnets: Subnet[] = [
  n({ id: 'subnet-prod', displayName: 'Production Subnet', cidr: '10.10.0.0/24', mask: '255.255.255.0', gateway: '10.10.0.1',
    siteId: 'site-nyc', vlanId: 'VLAN-100',
    nodeType: NodeType.Subnet, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'subnet-dev', displayName: 'Development Subnet', cidr: '10.30.0.0/24', mask: '255.255.255.0', gateway: '10.30.0.1',
    siteId: 'site-nyc', vlanId: 'VLAN-200',
    nodeType: NodeType.Subnet, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Linux Users ─────────────────────────────────────────────────
export const linuxUsers: LinuxUser[] = [
  n({ id: 'luser-david', displayName: 'dmiller', uid: 1001, gid: 1001, homeDirectory: '/home/dmiller', shell: '/bin/bash',
    groupIds: ['lgroup-admins'], locked: false, lastPasswordChange: '2024-06-15T00:00:00Z',
    nodeType: NodeType.LinuxUser, sourceSystem: SourceSystem.FreeIPA,
    metadata: { adUserId: 'user-007' }, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'luser-kevin', displayName: 'kpatel', uid: 1002, gid: 1002, homeDirectory: '/home/kpatel', shell: '/bin/zsh',
    groupIds: ['lgroup-devs'], locked: false, lastPasswordChange: '2024-08-01T00:00:00Z',
    nodeType: NodeType.LinuxUser, sourceSystem: SourceSystem.FreeIPA,
    metadata: { adUserId: 'user-009' }, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'luser-rachel', displayName: 'rgreen', uid: 1003, gid: 1002, homeDirectory: '/home/rgreen', shell: '/bin/bash',
    groupIds: ['lgroup-devs'], locked: false, lastPasswordChange: '2024-07-20T00:00:00Z',
    nodeType: NodeType.LinuxUser, sourceSystem: SourceSystem.FreeIPA,
    metadata: { adUserId: 'user-010' }, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Linux Groups ────────────────────────────────────────────────
export const linuxGroups: LinuxGroup[] = [
  n({ id: 'lgroup-admins', displayName: 'linux-admins', gid: 1001, memberIds: ['luser-david'],
    nodeType: NodeType.LinuxGroup, sourceSystem: SourceSystem.FreeIPA,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'lgroup-devs', displayName: 'linux-developers', gid: 1002, memberIds: ['luser-kevin', 'luser-rachel'],
    nodeType: NodeType.LinuxGroup, sourceSystem: SourceSystem.FreeIPA,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'lgroup-sudo', displayName: 'wheel', gid: 10, memberIds: [],
    nodeType: NodeType.LinuxGroup, sourceSystem: SourceSystem.Linux,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
]

// ── Sudo Policies ───────────────────────────────────────────────
export const sudoPolicies: SudoPolicy[] = [
  n({ id: 'sudo-full-admin', displayName: 'Full Administrative Sudo', userIds: [], groupIds: ['lgroup-admins'],
    hostIds: ['host-dev-01', 'host-mon-01'], commands: ['ALL'], nopasswd: true, sudoersPath: '/etc/sudoers.d/admins',
    nodeType: NodeType.SudoPolicy, sourceSystem: SourceSystem.Linux,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'sudo-service-restart', displayName: 'Service Restart Only', userIds: [], groupIds: ['lgroup-devs'],
    hostIds: ['host-dev-01'], runAsUsers: ['root'], commands: ['/usr/bin/systemctl restart *', '/usr/bin/systemctl status *'],
    nopasswd: false, sudoersPath: '/etc/sudoers.d/service-restart',
    nodeType: NodeType.SudoPolicy, sourceSystem: SourceSystem.Linux,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
]

// ── SSH Keys ────────────────────────────────────────────────────
export const sshKeys: SSHKey[] = [
  n({ id: 'sshkey-david-ed25519', displayName: 'David Miller Ed25519 Key', fingerprint: 'SHA256:abc123def456ghi789jkl',
    algorithm: 'Ed25519', keySize: 256, ownerId: 'luser-david', lastUsed: '2024-09-10T08:30:00Z',
    nodeType: NodeType.SSHKey, sourceSystem: SourceSystem.Linux,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'sshkey-kevin-rsa', displayName: 'Kevin Patel RSA Key', fingerprint: 'SHA256:mno456pqr789stu012vwx',
    algorithm: 'RSA', keySize: 4096, ownerId: 'luser-kevin', lastUsed: '2024-09-09T14:15:00Z',
    nodeType: NodeType.SSHKey, sourceSystem: SourceSystem.Linux,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    enabled: true, deleted: false, critical: false }),
]

// ── Applications ────────────────────────────────────────────────
export const applications: Application[] = [
  n({ id: 'app-employee-portal', displayName: 'Employee Portal', version: '3.2.1', vendor: 'NexusCore Internal',
    url: 'https://portal.nexuscore.com', environment: 'Production', authenticationMethod: 'SAML2', ssoEnabled: true, mfaRequired: false,
    nodeType: NodeType.Application, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'app-payment-gateway', displayName: 'Payment Gateway', version: '4.0.0', vendor: 'NexusCore Financial',
    url: 'https://payments.nexuscore.com', environment: 'Production', authenticationMethod: 'OAuth2', ssoEnabled: true, mfaRequired: true,
    nodeType: NodeType.Application, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'app-crm', displayName: 'Customer Relationship Management', version: '2.1.0', vendor: 'SalesForce',
    url: 'https://crm.nexuscore.com', environment: 'Production', authenticationMethod: 'SAML2', ssoEnabled: true, mfaRequired: true,
    nodeType: NodeType.Application, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'app-idp', displayName: 'Identity Provider', version: '5.0.0', vendor: 'NexusCore Internal',
    url: 'https://idp.nexuscore.com', environment: 'Production', authenticationMethod: 'OIDC', ssoEnabled: true, mfaRequired: true,
    nodeType: NodeType.Application, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
]

// ── Databases ───────────────────────────────────────────────────
export const databases: Database[] = [
  n({ id: 'db-portal', displayName: 'Portal Database', engine: 'PostgreSQL', version: '15.4', hostId: 'host-db-prod',
    port: 5432, databaseName: 'nexus_portal', encrypted: true, sslEnabled: true, backupEnabled: true,
    nodeType: NodeType.Database, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'db-payments', displayName: 'Payments Database', engine: 'Oracle', version: '19c', hostId: 'host-db-prod',
    port: 1521, databaseName: 'NEXPAY', encrypted: true, sslEnabled: true, backupEnabled: true,
    nodeType: NodeType.Database, sourceSystem: SourceSystem.Oracle,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'db-crm', displayName: 'CRM Database', engine: 'PostgreSQL', version: '14.10', hostId: 'host-db-prod',
    port: 5432, databaseName: 'nexus_crm', encrypted: true, sslEnabled: true, backupEnabled: true,
    nodeType: NodeType.Database, sourceSystem: SourceSystem.PostgreSQL,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: true }),
]

// ── Business Services ──────────────────────────────────────────
export const businessServices: BusinessService[] = [
  n({ id: 'bsvc-hris', displayName: 'HR Information System', criticality: 'High', sla: '99.9%',
    departmentId: 'dept-hr', complianceFrameworks: ['SOX', 'GDPR'], rto: '4h', rpo: '1h',
    nodeType: NodeType.BusinessService, sourceSystem: SourceSystem.Manual,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'bsvc-payments', displayName: 'Payment Processing', criticality: 'Critical', sla: '99.999%',
    departmentId: 'dept-fin', complianceFrameworks: ['PCI-DSS', 'SOX'], rto: '15m', rpo: '5m',
    nodeType: NodeType.BusinessService, sourceSystem: SourceSystem.Manual,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Critical,
    enabled: true, deleted: false, critical: true }),
  n({ id: 'bsvc-crm', displayName: 'Customer Management', criticality: 'High', sla: '99.95%',
    departmentId: 'dept-it', complianceFrameworks: ['GDPR'], rto: '2h', rpo: '30m',
    nodeType: NodeType.BusinessService, sourceSystem: SourceSystem.Manual,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
]

// ── Service Accounts ────────────────────────────────────────────
export const serviceAccounts: ServiceAccount[] = [
  n({ id: 'svcacct-backup', displayName: 'svc_backup', principalName: 'svc_backup@NEXUSCORP',
    domainId: 'dom-nexus', managedBy: 'user-001', supportsKerberos: true, supportsNtlm: false, passwordLastRotated: '2024-08-01T00:00:00Z',
    nodeType: NodeType.ServiceAccount, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
  n({ id: 'svcacct-monitoring', displayName: 'svc_monitor', principalName: 'svc_monitor@NEXUSCORP',
    domainId: 'dom-nexus', managedBy: 'user-002', allowedHostIds: ['host-mon-01'], supportsKerberos: true, supportsNtlm: true, passwordLastRotated: '2024-06-01T00:00:00Z',
    nodeType: NodeType.ServiceAccount, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.High,
    enabled: true, deleted: false, critical: false }),
]

// ── Managed Service Account ─────────────────────────────────────
export const managedServiceAccounts: ManagedServiceAccount[] = [
  n({ id: 'msvcacct-sql', displayName: 'gMSA_SQL_SVC', hostId: 'computer-sql-01', domainId: 'dom-nexus',
    groupManaged: true, dnsHostName: 'gmsa-sql.nexuscore.com', samAccountName: 'gMSA_SQL_SVC$', sid: 'S-1-5-21-3623811015-3361044348-30300820-1234',
    managedPasswordIntervalDays: 30,
    nodeType: NodeType.ManagedServiceAccount, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    enabled: true, deleted: false, critical: false }),
]

// ── GPOs ────────────────────────────────────────────────────────
export const gpos: GroupPolicy[] = [
  n({ id: 'gpo-security-baseline', displayName: 'Security Baseline Policy', domainId: 'dom-nexus',
    organizationalUnitIds: ['ou-servers'], enforced: true, enabled: true, revisionNumber: 5,
    computerSettings: { passwordPolicy: { minLength: 14, complexity: true }, auditPolicy: { logonEvents: 'Success,Failure' } },
    nodeType: NodeType.GroupPolicy, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Medium,
    deleted: false, critical: true }),
  n({ id: 'gpo-windows-update', displayName: 'Windows Update Policy', domainId: 'dom-nexus',
    organizationalUnitIds: ['ou-servers'], enforced: false, enabled: true, revisionNumber: 3,
    computerSettings: { windowsUpdate: { autoUpdate: true, updateDay: 'Tuesday' } },
    nodeType: NodeType.GroupPolicy, sourceSystem: SourceSystem.ActiveDirectory,
    metadata: {}, createdAt: TS, updatedAt: TS, status: AccountStatus.Active, riskLevel: RiskLevel.Low,
    deleted: false, critical: false }),
]

// ── Aggregate ───────────────────────────────────────────────────
export const allNodes = {
  forest: [forest],
  domain: [domain],
  organizationalUnits,
  departments,
  teams,
  managers,
  users,
  groups,
  roles,
  permissions,
  computers: computers,
  hosts,
  operatingSystems,
  site: [site],
  subnets,
  linuxUsers,
  linuxGroups,
  sudoPolicies,
  sshKeys,
  applications,
  databases,
  businessServices,
  serviceAccounts,
  managedServiceAccounts,
  gpos,
}

export const allNodesFlat: Array<{ id: string; displayName: string; nodeType: NodeType }> =
  Object.values(allNodes).flat()
