import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { AttackPathDetails,AttackPathList,AttackPathSearch,AttackPathSummary,PathFilters,PrivilegedTargetList } from '../components/attack-path'
import { attackPathExportUrl,filterAttackPaths,getAttackPathHistory,getAttackSummary,getBlastRadius,getChokePoints,getPrivilegedTargets,searchAttackPaths } from '../services/attackPathApi'
import type { AttackPath,AttackPathRun,AttackSearch,AttackSummary,BlastRadius,ChokePoint } from '../types/attackPath'
const initial:AttackSearch={sourceNodeId:'',maxDepth:6,maxPaths:25,directed:true,algorithm:'shortest'}
export function AttackPathsPage(){
  const[params]=useSearchParams(),[query,setQuery]=useState<AttackSearch>(()=>({...initial,sourceNodeId:params.get('sourceNodeId')??'',targetNodeId:params.get('targetNodeId')??undefined}))
  const[paths,setPaths]=useState<AttackPath[]>([]),[summary,setSummary]=useState<AttackSummary|null>(null),[targets,setTargets]=useState<any[]>([]),[history,setHistory]=useState<AttackPathRun[]>([]),[chokes,setChokes]=useState<ChokePoint[]>([]),[radius,setRadius]=useState<BlastRadius|null>(null),[selected,setSelected]=useState<AttackPath|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[type,setType]=useState(''),[minScore,setMinScore]=useState(0)
  useEffect(()=>{void Promise.all([getAttackSummary().then(setSummary),getPrivilegedTargets().then(setTargets),getAttackPathHistory().then(setHistory)]).catch(()=>undefined)},[])
  const run=async()=>{setLoading(true);setError('');try{const[result,blast]=await Promise.all([searchAttackPaths(query),getBlastRadius(query.sourceNodeId!,query)]);setPaths(result.paths);setRadius(blast);const[summaryResult,historyResult,chokeResult]=await Promise.all([getAttackSummary(),getAttackPathHistory(),getChokePoints(query)]);setSummary(summaryResult);setHistory(historyResult);setChokes(chokeResult)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  const visible=useMemo(()=>filterAttackPaths(paths,type,minScore),[paths,type,minScore])
  return <div className="mx-auto max-w-[1500px] space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Enterprise Attack Path Engine</h1><p className="mt-1 text-sm text-gray-500">Analyze identity, privilege, application, and database reachability with explainable risk scoring.</p></div><div className="flex gap-2"><a className="rounded border border-border px-3 py-2 text-xs text-primary"href={attackPathExportUrl('json')}>Export JSON</a><a className="rounded border border-border px-3 py-2 text-xs text-primary"href={attackPathExportUrl('csv')}>Export CSV</a></div></header><AttackPathSearch value={query}onChange={setQuery}onSearch={()=>void run()}loading={loading}/>{error&&<div role="alert"className="rounded border border-danger/40 bg-danger/10 p-3 text-danger">{error}<button onClick={()=>void run()}className="ml-3 underline">Retry</button></div>}{summary&&<AttackPathSummary summary={summary}/>}<div className="grid gap-4 xl:grid-cols-[1fr_20rem]"><div><div className="mb-3 flex items-center justify-between"><span className="text-sm text-gray-500">{visible.length} paths</span><PathFilters type={type}minScore={minScore}onType={setType}onScore={setMinScore}/></div>{loading?<div className="h-48 animate-pulse rounded-xl bg-white/5"/>:<AttackPathList paths={visible}onSelect={setSelected}/>}</div><div className="space-y-4"><PrivilegedTargetList targets={targets}/>{radius&&<section className="rounded-xl border border-border bg-card p-4"><h2 className="text-sm font-semibold">Blast radius</h2><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Metric label="Reachable"value={radius.reachableNodeCount}/><Metric label="Privileged"value={radius.privilegedTargetCount}/><Metric label="Max depth"value={radius.maximumDepth}/></div></section>}{chokes.length>0&&<section className="rounded-xl border border-border bg-card p-4"><h2 className="text-sm font-semibold">Choke points</h2><div className="mt-3 space-y-2">{chokes.slice(0,5).map(item=><div key={item.node.id}className="flex justify-between rounded bg-surface p-2 text-xs"><span>{item.node.displayName}<small className="block text-gray-500">{item.pathCount} paths</small></span><b>{item.percentage}%</b></div>)}</div></section>}<section className="rounded-xl border border-border bg-card p-4"><h2 className="text-sm font-semibold">Analysis history</h2><div className="mt-3 space-y-2">{history.slice(0,8).map(run=><div key={run.id}className="flex justify-between text-xs"><span>{new Date(run.startedAt).toLocaleString()}<small className="block text-gray-500">{run.status}</small></span><b>{run.pathCount}</b></div>)}</div></section></div></div><AttackPathDetails path={selected}onClose={()=>setSelected(null)}/></div>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded bg-surface p-2"><b className="block text-lg">{value}</b><span className="text-[10px] text-gray-500">{label}</span></div>}
