import { useEffect, useState } from 'react'
import { DEFAULT_SETTINGS, loadSettings, saveSettings, type FrontendSettings } from '../services/navigation'
import { getSettingsHistory, getWorkspaceSettings, resetWorkspaceSettings, updateWorkspaceSettings } from '../services/settingsApi'
import { PageTitle } from './Identities'
import { Neo4jStatusBadge } from '../components/Neo4jStatusBadge'
import { DEMO_DATA_ENABLED } from '../services/runtimeConfig'

type HistoryEvent = { id:string; actor:string; action:string; changes:Record<string,unknown>; createdAt:string }
const safeSettings=(value:FrontendSettings):FrontendSettings=>DEMO_DATA_ENABLED?value:{...value,graphSource:value.graphSource==='mock'?'neo4j':value.graphSource,autoFallback:false}

export function SettingsPage(){
  const[settings,setSettings]=useState<FrontendSettings>(()=>safeSettings(typeof localStorage==='undefined'?DEFAULT_SETTINGS:loadSettings(localStorage)))
  const[history,setHistory]=useState<HistoryEvent[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false)
  const[error,setError]=useState(''),[notice,setNotice]=useState('')
  useEffect(()=>{void Promise.all([getWorkspaceSettings(),getSettingsHistory()]).then(([remote,audit])=>{const safe=safeSettings(remote);setSettings(safe);setHistory(audit);saveSettings(localStorage,safe)}).catch(e=>setError(`${(e as Error).message}. Using settings saved on this device.`)).finally(()=>setLoading(false))},[])
  const update=(key:keyof FrontendSettings,value:unknown)=>{setSettings(current=>({...current,[key]:value}));setDirty(true);setNotice('')}
  const save=async()=>{setSaving(true);setError('');try{const remote=safeSettings(await updateWorkspaceSettings(safeSettings(settings)));setSettings(remote);saveSettings(localStorage,remote);setHistory(await getSettingsHistory());setDirty(false);setNotice('Workspace settings saved for all administrators.')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  const reset=async()=>{setSaving(true);setError('');try{const remote=safeSettings(await resetWorkspaceSettings());setSettings(remote);saveSettings(localStorage,remote);setHistory(await getSettingsHistory());setDirty(false);setNotice('Enterprise defaults restored.')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  const selects:[string,keyof FrontendSettings,(string|number)[]][]=[['Default graph source','graphSource',DEMO_DATA_ENABLED?['mock','imported','neo4j']:['imported','neo4j']],['Default layout','layout',['force','hierarchy','radial','concentric']],['Page size','pageSize',[10,25,50,100]],['Neo4j initial node limit','neo4jNodeLimit',[100,300,500,1000]],['Neo4j relationship limit','neo4jRelationshipLimit',[500,1200,2500,5000]],['API request timeout','apiTimeoutMs',[5000,10000,20000,30000]]]
  const toggles:[string,keyof FrontendSettings][]=[['Show graph labels','showLabels'],['Enable animations','animations'],['Compact mode','compact']]
  if(DEMO_DATA_ENABLED)toggles.push(['Auto-fallback to Mock Enterprise','autoFallback'])
  return <div className="mx-auto max-w-4xl space-y-5"><PageTitle title="Administration & Workspace Settings" subtitle="Manage shared graph behavior, limits, resilience, and presentation defaults"/>{loading&&<div className="h-32 animate-pulse rounded-xl bg-white/5"/>}{error&&<div role="alert" className="rounded border border-warning/40 bg-warning/10 p-3 text-xs text-warning">{error}</div>}<div className="flex items-center justify-between rounded-xl border border-border bg-card p-4"><span className="text-sm text-gray-300">Neo4j Live status</span><Neo4jStatusBadge details/></div><div className="divide-y divide-border rounded-xl border border-border bg-card">{selects.map(([label,key,options])=><label key={key} className="flex items-center justify-between gap-4 p-4 text-sm text-gray-300"><span>{label}</span><select disabled={loading||saving} value={String(settings[key])} onChange={event=>update(key,typeof options[0]==='number'?Number(event.target.value):event.target.value)} className="rounded border border-border bg-surface px-3 py-2">{options.map(option=><option key={option} value={option}>{option}{key==='apiTimeoutMs'?' ms':''}</option>)}</select></label>)}{toggles.map(([label,key])=><label key={key} className="flex items-center justify-between p-4 text-sm text-gray-300"><span>{label}</span><input disabled={loading||saving} type="checkbox" checked={Boolean(settings[key])} onChange={event=>update(key,event.target.checked)} className="h-4 w-4 accent-primary"/></label>)}</div><div className="flex items-center justify-between"><span className="text-xs text-success">{notice||(!dirty&&!loading?'Settings synchronized.':'')}</span><div className="flex gap-2"><button disabled={saving||loading} onClick={()=>void reset()} className="rounded border border-border px-4 py-2 text-xs disabled:opacity-50">Restore defaults</button><button disabled={!dirty||saving||loading} onClick={()=>void save()} className="rounded bg-primary px-4 py-2 text-xs text-white disabled:opacity-50">{saving?'Saving…':'Save settings'}</button></div></div><section className="rounded-xl border border-border bg-card p-4"><h2 className="text-sm font-semibold">Change history</h2>{history.length===0?<p className="mt-3 text-xs text-gray-500">No administrative setting changes have been recorded.</p>:<div className="mt-3 divide-y divide-border">{history.slice(0,10).map(event=><div key={event.id} className="flex justify-between py-2 text-xs"><span>{event.action} by {event.actor}<small className="block text-gray-500">{Object.keys(event.changes).join(', ')||'Defaults confirmed'}</small></span><time className="text-gray-500">{new Date(event.createdAt).toLocaleString()}</time></div>)}</div>}</section></div>
}
