import { BadRequestException,Body,Controller,Get,HttpCode,NotFoundException,Param,Post,Query,Res } from '@nestjs/common';import type{Response}from'express';import { GraphService } from './graph.service';import type { PersistedGraphNode,PersistedGraphRelationship } from './repositories';import { EnterpriseGraphService } from './enterprise-graph.service'
const list=(value?:string)=>value?.split(',').map(item=>item.trim()).filter(Boolean);const number=(value:string|undefined,name:string)=>{if(value===undefined)return;const parsed=Number(value);if(!Number.isInteger(parsed)||parsed<0)throw new BadRequestException(`${name} must be a non-negative integer`);return parsed};const direction=(value?:string)=>{if(value===undefined)return;if(value!=='ASC'&&value!=='DESC')throw new BadRequestException('sortDirection must be ASC or DESC');return value};const nodeSort=(value?:string)=>{if(value===undefined)return;const allowed=['displayName','nodeType','sourceSystem','riskLevel','status'];if(!allowed.includes(value))throw new BadRequestException(`sortBy must be one of ${allowed.join(', ')}`);return value as any};const csv=(value:unknown)=>{const str=String(value??'');const escaped=str.replace(/"/g,'""');const prefixed=/^[=+\-@\t]/.test(escaped)?`'${escaped}`:escaped;return`"${prefixed}"`}
@Controller('graph')
export class GraphController{constructor(private readonly graph:GraphService,private readonly enterprise:EnterpriseGraphService){}
  @Get('explorer/nodes')exploreNodes(@Query()q:Record<string,string>){return this.graph.exploreNodes({query:q.q,nodeTypes:list(q.nodeTypes),sourceSystems:list(q.sourceSystems),riskLevels:list(q.riskLevels),statuses:list(q.statuses),limit:number(q.limit,'limit'),offset:number(q.offset,'offset'),sortBy:nodeSort(q.sortBy),sortDirection:direction(q.sortDirection)})}
  @Get('explorer/relationships')exploreRelationships(@Query()q:Record<string,string>){return this.graph.exploreRelationships({query:q.q,types:list(q.types),sourceSystems:list(q.sourceSystems),limit:number(q.limit,'limit'),offset:number(q.offset,'offset'),sortDirection:direction(q.sortDirection)})}
  @Get('explorer/nodes/export')async exportNodes(@Query()q:Record<string,string>,@Res()response:Response){const format=q.format??'json';if(!['json','csv'].includes(format))throw new BadRequestException('format must be json or csv');const result=await this.graph.exportNodes({query:q.q,nodeTypes:list(q.nodeTypes),sourceSystems:list(q.sourceSystems),riskLevels:list(q.riskLevels),statuses:list(q.statuses),sortBy:nodeSort(q.sortBy),sortDirection:direction(q.sortDirection)});response.setHeader('X-Total-Count',String(result.total));response.setHeader('X-Export-Truncated',String(result.truncated));response.setHeader('Content-Disposition',`attachment; filename="graph-nodes.${format}"`);if(format==='json')return response.json(result.items);response.type('text/csv');const rows=result.items.map(node=>[node.id,node.displayName,node.nodeType,node.sourceSystem,node.riskLevel,node.properties?.status]);return response.send([['id','displayName','nodeType','sourceSystem','riskLevel','status'],...rows].map(row=>row.map(csv).join(',')).join('\n'))}
  @Get('explorer/relationships/export')async exportRelationships(@Query()q:Record<string,string>,@Res()response:Response){const format=q.format??'json';if(!['json','csv'].includes(format))throw new BadRequestException('format must be json or csv');const result=await this.graph.exportRelationships({query:q.q,types:list(q.types),sourceSystems:list(q.sourceSystems),sortDirection:direction(q.sortDirection)});response.setHeader('X-Total-Count',String(result.total));response.setHeader('X-Export-Truncated',String(result.truncated));response.setHeader('Content-Disposition',`attachment; filename="graph-relationships.${format}"`);if(format==='json')return response.json(result.items);response.type('text/csv');const rows=result.items.map(item=>[item.relationship.id,item.sourceName,item.relationship.source,item.relationship.relationshipType,item.targetName,item.relationship.target,item.relationship.sourceSystem]);return response.send([['id','sourceName','sourceId','relationshipType','targetName','targetId','sourceSystem'],...rows].map(row=>row.map(csv).join(',')).join('\n'))}
  @Get('nodes/:id')async node(@Param('id')id:string){const node=await this.graph.getNodeById(id);if(!node)throw new NotFoundException('Graph node not found');return node}
  @Get('nodes/:id/neighbors')neighbors(@Param('id')id:string,@Query('direction')direction?:'incoming'|'outgoing'|'both',@Query('limit')limit?:string,@Query('depth')depth?:string){return this.graph.getNeighbors(id,{direction,limit:limit?Number(limit):undefined},depth?Number(depth):1)}
  @Get('search')search(@Query('q')query='',@Query('nodeType')nodeType?:string,@Query('sourceSystem')sourceSystem?:string,@Query('risk')risk?:string,@Query('limit')limit?:string,@Query('offset')offset?:string){return this.graph.searchNodes(query,{nodeTypes:nodeType?[nodeType]:[],sourceSystems:sourceSystem?[sourceSystem]:[],riskLevels:risk?[risk]:[],limit:limit?Number(limit):undefined,offset:offset?Number(offset):undefined})}
  @Get('subgraph')subgraph(@Query('ids')ids='',@Query('depth')depth?:string,@Query('limit')limit?:string,@Query('relationshipLimit')relationshipLimit?:string,@Query('nodeType')nodeType?:string,@Query('sourceSystem')sourceSystem?:string,@Query('risk')risk?:string,@Query('status')status?:string){return this.graph.getSubgraph(ids.split(',').filter(Boolean),{depth:depth?Number(depth):undefined,limit:limit?Number(limit):undefined},{limit:limit?Number(limit):undefined,relationshipLimit:relationshipLimit?Number(relationshipLimit):undefined,nodeType,sourceSystem,risk,status})}
  @Get('dashboard-summary')dashboard(@Query('nodeType')nodeType?:string,@Query('sourceSystem')sourceSystem?:string,@Query('risk')risk?:string,@Query('status')status?:string){return this.graph.getDashboardSummary({nodeType,sourceSystem,risk,status})}
  @Get('stats')stats(){return this.graph.getGraphStats()}
  @Get('statistics')statistics(){return this.enterprise.statistics()}
  @Get('versions')versions(@Query('limit')limit?:string){return this.enterprise.listVersions(Number(limit??50))}
  @Post('versions')@HttpCode(200)apply(@Body()body:any){return this.enterprise.apply(body)}
  @Get('snapshots')snapshots(){return this.enterprise.listSnapshots()}
  @Post('snapshots')@HttpCode(200)snapshot(@Body()body:{name?:string}={}){return this.enterprise.createSnapshot(body.name)}
  @Get('snapshots/diff')diff(@Query('from')from:string,@Query('to')to:string){return this.enterprise.diff(from,to)}
  @Get('shortest-path')shortest(@Query('source')source:string,@Query('target')target:string,@Query('maxDepth')depth?:string){return this.enterprise.shortestPath(source,target,Number(depth??8))}
  @Get('blast-radius/:id')blast(@Param('id')id:string,@Query('maxDepth')depth?:string){return this.enterprise.blastRadius(id,Number(depth??4))}
  @Post('nodes/batch')@HttpCode(200)nodes(@Body()body:{nodes:PersistedGraphNode[]}){return this.graph.upsertNodes(body.nodes??[])}
  @Post('relationships/batch')@HttpCode(200)relationships(@Body()body:{relationships:PersistedGraphRelationship[]}){return this.graph.upsertRelationships(body.relationships??[])}}
