import { lazy, memo, Suspense } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, AppWindow, Building2 as BriefcaseBusiness, UserX as CircleOff, Server as Database, AlertTriangle as FileWarning, Key as KeyRound, Monitor, Shield as ShieldAlert, Users as UserCheck, Users } from 'lucide-react'
import type { GraphData } from '../../types/graph'
import { KpiCard } from './KpiCard'; import { IdentityDistribution, Panel } from './IdentityDistribution'; import { RiskOverview } from './RiskOverview'; import { ComplianceOverview } from './ComplianceOverview'; import { LatestChanges } from './LatestChanges'; import { RecentImports } from './RecentImports'; import { PipelineOverview } from './PipelineOverview'; import { QuickActions } from './QuickActions'; import { RecentInvestigations } from './RecentInvestigations'
const GraphPreview = lazy(() => import('./GraphPreview'))
const spark = [28, 36, 31, 49, 45, 58, 66]

export const DashboardGrid = memo(function DashboardGrid({ data }: { data: GraphData }) {
  const navigate = useNavigate(); const count = (types: string[]) => data.nodes.filter((node) => types.includes(node.nodeType)).length
  const identities = count(['USER','LINUX_USER','SERVICE_ACCOUNT','MANAGED_SERVICE_ACCOUNT']); const risks = (level: string) => data.nodes.filter((node) => node.riskLevel === level).length
  const kpis = [{ label: 'Total Identities', value: identities, trend: '+4.8%', icon: Users, color: '#38bdf8' }, { label: 'Active Accounts', value: Math.max(0, identities - 18), trend: '+2.1%', icon: UserCheck, color: '#22c55e' }, { label: 'Disabled Accounts', value: 18, trend: '-6.4%', icon: CircleOff, color: '#94a3b8' }, { label: 'Privileged Accounts', value: Math.max(12, count(['ROLE','PERMISSION'])), trend: '+1.2%', icon: KeyRound, color: '#8b5cf6' }, { label: 'Applications', value: count(['APPLICATION']), trend: '+3.0%', icon: AppWindow, color: '#06b6d4' }, { label: 'Hosts', value: count(['HOST','COMPUTER']), trend: '+1.8%', icon: Monitor, color: '#a855f7' }, { label: 'Databases', value: count(['DATABASE']), trend: '+0.6%', icon: Database, color: '#ec4899' }, { label: 'Business Services', value: count(['BUSINESS_SERVICE']), trend: '+2.5%', icon: BriefcaseBusiness, color: '#6366f1' }, { label: 'Critical Risks', value: risks('CRITICAL') || 12, trend: '-8.3%', icon: ShieldAlert, color: '#ef4444' }, { label: 'Open Findings', value: 146, trend: '-3.7%', icon: FileWarning, color: '#f97316' }]
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">{kpis.map((kpi, index) => <KpiCard key={kpi.label} {...kpi} points={spark.map((point) => point + index % 4 * 3)} />)}</div><div className="grid gap-4 lg:grid-cols-3"><IdentityDistribution/><RiskOverview/><ComplianceOverview/></div><div className="grid gap-4 xl:grid-cols-3"><Suspense fallback={<div className="h-[425px] animate-pulse rounded-xl bg-white/5 xl:col-span-2"/>}><GraphPreview data={data}/></Suspense><LatestChanges/></div><Panel title="Risk Findings"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Critical',12,'#ef4444'],['High',38,'#f97316'],['Medium',96,'#eab308'],['Low',184,'#22c55e']].map(([label,value,color]) => <button key={label as string} onClick={() => navigate(`/graph?risk=${String(label).toUpperCase()}`)} className="rounded-lg border border-border bg-surface/50 p-4 text-left transition hover:-translate-y-0.5 hover:border-white/20"><AlertTriangle className="h-4 w-4" style={{ color: color as string }}/><div className="mt-3 text-2xl font-semibold text-gray-100">{value}</div><div className="text-xs" style={{ color: color as string }}>{label} findings</div></button>)}</div></Panel><div className="grid gap-4 xl:grid-cols-2"><RecentImports/><PipelineOverview/></div><QuickActions/><RecentInvestigations/></div>
})
