import { memo, type ReactNode } from 'react'

const colors = ['#3b82f6', '#8b5cf6', '#14b8a6', '#f59e0b', '#ec4899', '#64748b']
export const IdentityDistribution = memo(function IdentityDistribution({ counts, onSelect }: { counts: Record<string, number>; onSelect: (source: string) => void }) {
  const total = Object.values(counts).reduce((sum, count) => sum + count, 0)
  const segments = Object.entries(counts).filter(([, count]) => count > 0).sort((a, b) => b[1] - a[1]).slice(0, 6).map(([source, count], index) => ({ source, name: source.replace(/_/g, ' '), value: total ? count / total * 100 : 0, count, color: colors[index] }))
  let offset = 0
  return <Panel title="Identity Distribution">{segments.length === 0 ? <p className="py-12 text-center text-xs text-gray-500">No source-system data.</p> : <div className="flex items-center justify-center gap-7"><svg viewBox="0 0 42 42" className="h-32 w-32 -rotate-90" aria-label="Identity source distribution">{segments.map((segment) => { const current = offset; offset += segment.value; return <circle key={segment.source} cx="21" cy="21" r="15.9" fill="none" stroke={segment.color} strokeWidth="5" strokeDasharray={`${segment.value} ${100 - segment.value}`} strokeDashoffset={-current} /> })}<circle cx="21" cy="21" r="12" fill="#111827" /></svg><div className="space-y-1">{segments.map((segment) => <button key={segment.source} onClick={() => onSelect(segment.source)} className="flex w-40 items-center justify-between rounded px-1 py-1 text-xs hover:bg-white/5 focus:outline-none focus:ring-1 focus:ring-primary"><span className="flex min-w-0 items-center gap-2 text-gray-400"><i className="h-2 w-2 shrink-0 rounded-full" style={{ background: segment.color }} /><span className="truncate">{segment.name}</span></span><b className="text-gray-200">{segment.count.toLocaleString()}</b></button>)}</div></div>}</Panel>
})
export function Panel({ title, children, className = '', action }: { title: string; children: ReactNode; className?: string; action?: ReactNode }) { return <section className={`rounded-xl border border-border bg-card/75 p-5 shadow-glass ${className}`}><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold text-gray-200">{title}</h2>{action}</div>{children}</section> }
