import assert from'node:assert/strict';import{describe,it}from'node:test';import{FindingRepository}from'../finding.repository';import{RiskScoringService}from'../risk-scoring.service';import{RiskService,stableFindingId}from'../risk.service';import{FindingStatus,type GraphSnapshot}from'../risk.types';import{riskRules}from'../rules'
const node=(id:string,nodeType='USER',properties:Record<string,unknown>={},riskLevel='NONE',sourceSystem='ACTIVE_DIRECTORY')=>({id,displayName:id,nodeType,sourceSystem,riskLevel,properties});const rel=(id:string,source:string,target:string,relationshipType:string,properties:Record<string,unknown>={})=>({id,source,target,relationshipType,sourceSystem:'ACTIVE_DIRECTORY',properties});const find=(id:string)=>riskRules.find(r=>r.id===id)!
describe('risk intelligence foundation',()=>{
 it('creates stable IDs and prevents duplicates',async()=>{assert.equal(stableFindingId('r',['b','a']),stableFindingId('r',['a','b']));const graph:GraphSnapshot={nodes:[node('u','USER',{status:'DISABLED'})],relationships:[rel('a','u','app','HAS_ACCESS_TO'),node('app','APPLICATION') as any].filter(x=>(x as any).relationshipType) as any};const repo=new FindingRepository(),service=new RiskService({load:async()=>graph}as any,repo,new RiskScoringService());await service.scan();await service.scan();assert.equal(service.list({limit:500}).filter(f=>f.ruleId==='disabled-active-access').length,1)})
 it('keeps score within boundaries',()=>{const score=new RiskScoringService().score({nodes:[node('u','SERVICE_ACCOUNT',{privileged:true,status:'DISABLED',environment:'production',department:'finance',rootAccess:true},'CRITICAL')],relationships:[]},{nodes:['u']},90);assert.equal(score.totalScore,100);assert.equal(score.severity,'CRITICAL')})
 it('detects disabled access and inherited Domain Admin',()=>{const graph:GraphSnapshot={nodes:[node('u','USER',{status:'DISABLED'}),node('nested','GROUP'),node('da','GROUP',{privileged:true})],relationships:[rel('a','u','nested','MEMBER_OF'),rel('b','nested','da','MEMBER_OF')]};assert.equal(find('disabled-active-access').detect(graph,6).length,1);assert.equal(find('inherited-domain-admin').detect({...graph,nodes:graph.nodes.map(n=>n.id==='da'?{...n,displayName:'Domain Admins'}:n)},6).length,1)})
 it('detects unrestricted sudo, circular groups, and SoD',()=>{const graph:GraphSnapshot={nodes:[node('sudo','SUDO_POLICY',{commands:'ALL'}),node('g1','GROUP'),node('g2','GROUP'),node('u'),node('approve','PERMISSION'),node('payment','PERMISSION')],relationships:[rel('g1g2','g1','g2','MEMBER_OF'),rel('g2g1','g2','g1','MEMBER_OF'),rel('approve-r','u','approve','HAS_PERMISSION'),rel('pay-r','u','payment','HAS_PERMISSION')]};assert.equal(find('unrestricted-sudo').detect(graph,6).length,1);assert.ok(find('circular-group-membership').detect(graph,6).length);assert.equal(find('finance-approval-payment-sod').detect(graph,6).length,1)})
 it('preserves status and produces filtered summary counts',async()=>{const graph:GraphSnapshot={nodes:[node('u','USER',{status:'DISABLED',privileged:true})],relationships:[]};const repo=new FindingRepository(),service=new RiskService({load:async()=>graph}as any,repo,new RiskScoringService());await service.scan();const finding=service.list({ruleId:'disabled-privileged-account'})[0];service.setStatus(finding.id,FindingStatus.ACKNOWLEDGED);await service.scan();assert.equal(service.get(finding.id).status,FindingStatus.ACKNOWLEDGED);assert.equal(service.list({status:FindingStatus.ACKNOWLEDGED}).length,1);assert.ok(service.summary().countsBySeverity.CRITICAL>=1)})
 it('uses disabled-mode memory fallback',async()=>{let requested='';const source={load:async(mode:string)=>{requested=mode;return{nodes:[],relationships:[]}}};const service=new RiskService(source as any,new FindingRepository(),new RiskScoringService());await service.scan({graphSource:'memory'});assert.equal(requested,'memory')})
})
