import assert from'node:assert/strict';import{describe,it}from'node:test';import{FindingRepository}from'../finding.repository';import{RiskScoringService}from'../risk-scoring.service';import{RiskService,stableFindingId}from'../risk.service';import{FindingStatus,type GraphSnapshot}from'../risk.types';import{riskRules}from'../rules'
const node=(id:string,nodeType='USER',properties:Record<string,unknown>={},riskLevel='NONE',sourceSystem='ACTIVE_DIRECTORY')=>({id,displayName:id,nodeType,sourceSystem,riskLevel,properties});const rel=(id:string,source:string,target:string,relationshipType:string,properties:Record<string,unknown>={})=>({id,source,target,relationshipType,sourceSystem:'ACTIVE_DIRECTORY',properties});const find=(id:string)=>riskRules.find(r=>r.id===id)!
describe('risk intelligence foundation',()=>{
 it('creates stable IDs and prevents duplicates',async()=>{assert.equal(stableFindingId('r',['b','a']),stableFindingId('r',['a','b']));const graph:GraphSnapshot={nodes:[node('u','USER',{status:'DISABLED'})],relationships:[rel('a','u','app','HAS_ACCESS_TO'),node('app','APPLICATION') as any].filter(x=>(x as any).relationshipType) as any};const repo=new FindingRepository(),service=new RiskService({load:async()=>graph}as any,repo,new RiskScoringService());await service.scan();await service.scan();assert.equal(service.list({limit:500}).filter(f=>f.ruleId==='disabled-active-access').length,1)})
 it('keeps score within boundaries',()=>{const score=new RiskScoringService().score({nodes:[node('u','SERVICE_ACCOUNT',{privileged:true,status:'DISABLED',environment:'production',department:'finance',rootAccess:true},'CRITICAL')],relationships:[]},{nodes:['u']},90);assert.equal(score.totalScore,100);assert.equal(score.severity,'CRITICAL')})
 it('detects disabled access and inherited Domain Admin',()=>{const graph:GraphSnapshot={nodes:[node('u','USER',{status:'DISABLED'}),node('nested','GROUP'),node('da','GROUP',{privileged:true})],relationships:[rel('a','u','nested','MEMBER_OF'),rel('b','nested','da','MEMBER_OF')]};assert.equal(find('disabled-active-access').detect(graph,6).length,1);assert.equal(find('inherited-domain-admin').detect({...graph,nodes:graph.nodes.map(n=>n.id==='da'?{...n,displayName:'Domain Admins'}:n)},6).length,1)})
 it('detects unrestricted sudo, circular groups, and SoD',()=>{const graph:GraphSnapshot={nodes:[node('sudo','SUDO_POLICY',{commands:'ALL'}),node('g1','GROUP'),node('g2','GROUP'),node('u'),node('approve','PERMISSION'),node('payment','PERMISSION')],relationships:[rel('g1g2','g1','g2','MEMBER_OF'),rel('g2g1','g2','g1','MEMBER_OF'),rel('approve-r','u','approve','HAS_PERMISSION'),rel('pay-r','u','payment','HAS_PERMISSION')]};assert.equal(find('unrestricted-sudo').detect(graph,6).length,1);assert.ok(find('circular-group-membership').detect(graph,6).length);assert.equal(find('finance-approval-payment-sod').detect(graph,6).length,1)})
 it('preserves status and produces filtered summary counts',async()=>{const graph:GraphSnapshot={nodes:[node('u','USER',{status:'DISABLED',privileged:true})],relationships:[]};const repo=new FindingRepository(),service=new RiskService({load:async()=>graph}as any,repo,new RiskScoringService());await service.scan();const finding=service.list({ruleId:'disabled-privileged-account'})[0];service.setStatus(finding.id,FindingStatus.ACKNOWLEDGED);await service.scan();assert.equal(service.get(finding.id).status,FindingStatus.ACKNOWLEDGED);assert.equal(service.list({status:FindingStatus.ACKNOWLEDGED}).length,1);assert.ok(service.summary().countsBySeverity.CRITICAL>=1)})
 it('uses disabled-mode memory fallback',async()=>{let requested='';const source={load:async(mode:string)=>{requested=mode;return{nodes:[],relationships:[]}}};const service=new RiskService(source as any,new FindingRepository(),new RiskScoringService());await service.scan({graphSource:'memory'});assert.equal(requested,'memory')})
 it('resolves findings that disappear and reopens them when they return',async()=>{let graph:GraphSnapshot={nodes:[node('u','USER',{status:'DISABLED',privileged:true})],relationships:[]};const repo=new FindingRepository(),service=new RiskService({load:async()=>graph}as any,repo,new RiskScoringService());const first=await service.scan({ruleIds:['disabled-privileged-account']});assert.equal(first.findingsDetected,1);graph={nodes:[],relationships:[]};const second=await service.scan({ruleIds:['disabled-privileged-account']});assert.equal(second.findingsResolved,1);assert.equal(service.list({ruleId:'disabled-privileged-account'})[0].status,FindingStatus.RESOLVED);graph={nodes:[node('u','USER',{status:'DISABLED',privileged:true})],relationships:[]};await service.scan({ruleIds:['disabled-privileged-account']});assert.equal(service.list({ruleId:'disabled-privileged-account'})[0].status,FindingStatus.OPEN)})
 it('records completed and failed scan audits',async()=>{let fail=false;const repo=new FindingRepository(),service=new RiskService({load:async()=>{if(fail)throw new Error('graph unavailable');return{nodes:[],relationships:[]}}}as any,repo,new RiskScoringService());const result=await service.scan();assert.equal(service.scanRun(result.scanId).status,'COMPLETED');fail=true;await assert.rejects(()=>service.scan(),/graph unavailable/);assert.equal(service.scans()[0].status,'FAILED')})
 it('prevents overlapping scans',async()=>{let release!:()=>void;const service=new RiskService({load:()=>new Promise(resolve=>{release=()=>resolve({nodes:[],relationships:[]})})}as any,new FindingRepository(),new RiskScoringService());const first=service.scan();await new Promise(resolve=>setTimeout(resolve,0));await assert.rejects(()=>service.scan(),/already running/);release();await first})
 it('propagates PostgreSQL failures from finding mutations',async()=>{const store={saveFinding:()=>undefined,flush:async()=>{throw new Error('finding persistence failed')}};const repo=new FindingRepository(store as any);repo.upsert({id:'f1',ruleId:'r1',title:'Risk',description:'Risk',category:'IDENTITY' as any,severity:'HIGH' as any,confidence:100,status:FindingStatus.OPEN,score:80,scoreFactors:[],affectedNodes:[],affectedRelationships:[],evidencePaths:[],sourceSystems:[],firstDetected:new Date().toISOString(),lastDetected:new Date().toISOString(),remediationGuidance:'Fix',metadata:{}});const service=new RiskService({}as any,repo,new RiskScoringService());await assert.rejects(()=>service.setStatus('f1',FindingStatus.ACKNOWLEDGED),/finding persistence failed/)})
})
