import { Injectable, NotFoundException, OnModuleInit, Optional } from '@nestjs/common'
import { Neo4jService } from '../neo4j'
import { RiskGraphSourceService, type GraphSnapshot } from '../risk'
import { OperationalStoreService } from '../database/operational-store.service'
import type { AttackPath, AttackPathRun, AttackPathSearch } from './attack-path.types'

export const ALLOWED_RELATIONSHIPS = ['MEMBER_OF','HAS_ROLE','GRANTS','HAS_ACCESS_TO','AUTHENTICATES_TO','HAS_SUDO_POLICY','HAS_SSH_KEY','TRUSTS','BELONGS_TO','REPORTS_TO','MANAGED_BY','RUNS_ON','SUPPORTS','USES','EXISTS_IN']
@Injectable()
export class AttackPathRepository implements OnModuleInit {
  private paths = new Map<string, AttackPath>(); private runs = new Map<string, AttackPathRun>(); private analysis?: { at:string;duration:number }
  constructor(private neo4j:Neo4jService,private source:RiskGraphSourceService,@Optional()private store?:OperationalStoreService){}
  async onModuleInit(){if(!this.store)return;const[paths,runs]=await Promise.all([this.store.loadPaths(),this.store.loadAttackPathRuns(200)]);this.paths=new Map(paths.map(row=>[row.id,row.payload as unknown as AttackPath]));this.runs=new Map(runs.map(row=>[row.id,row.payload as unknown as AttackPathRun]));const latest=[...this.runs.values()].find(run=>run.status==='COMPLETED');if(latest)this.analysis={at:latest.completedAt!,duration:latest.durationMs??0}}
  async startRun(run:AttackPathRun){this.runs.set(run.id,run);await this.store?.saveAttackPathRun({id:run.id,status:run.status,pathCount:0,durationMs:null,payload:run as unknown as Record<string,unknown>,startedAt:new Date(run.startedAt),completedAt:null})}
  async completeRun(id:string,paths:AttackPath[],duration:number){const run=this.runs.get(id);if(!run)return;Object.assign(run,{status:'COMPLETED',pathCount:paths.length,durationMs:duration,completedAt:new Date().toISOString()});paths.forEach(path=>this.paths.set(path.id,path));this.analysis={at:run.completedAt!,duration};if(this.store){await this.store.savePaths(paths.map(path=>({id:path.id,riskScore:path.totalRiskScore,payload:path as unknown as Record<string,unknown>,createdAt:new Date(path.createdAt)})));await this.store.saveAttackPathRun({id:run.id,status:run.status,pathCount:run.pathCount,durationMs:duration,payload:run as unknown as Record<string,unknown>,startedAt:new Date(run.startedAt),completedAt:new Date(run.completedAt!)})}}
  async failRun(id:string,error:string,duration:number){const run=this.runs.get(id);if(!run)return;Object.assign(run,{status:'FAILED',error,durationMs:duration,completedAt:new Date().toISOString()});await this.store?.saveAttackPathRun({id:run.id,status:run.status,pathCount:0,durationMs:duration,payload:run as unknown as Record<string,unknown>,startedAt:new Date(run.startedAt),completedAt:new Date(run.completedAt!)})}
  get(id:string){return this.paths.get(id)} list(){return[...this.paths.values()].sort((a,b)=>b.totalRiskScore-a.totalRiskScore||a.id.localeCompare(b.id))} latest(){return this.analysis}
  history(limit=50){return[...this.runs.values()].sort((a,b)=>b.startedAt.localeCompare(a.startedAt)).slice(0,Math.min(200,Math.max(1,limit)))}
  run(id:string){const run=this.runs.get(id);if(!run)throw new NotFoundException('Attack-path run not found');return run}
  async graph(request:AttackPathSearch):Promise<GraphSnapshot>{if(request.graphSource==='memory'||(request.graphSource!=='neo4j'&&!this.neo4j.isEnabled()))return this.source.load('memory');const depth=Math.min(12,Math.max(1,Math.trunc(request.maxDepth??6))),limit=Math.min(20000,Math.max(1000,Math.trunc(request.maxPaths??50)*100));const directed=request.directed!==false;const pattern=directed?`-[rels*1..${depth}]->`:`-[rels*1..${depth}]-`;const query=`MATCH path=(source:GraphNode)${pattern}(target:GraphNode) WHERE ($sourceId IS NULL OR source.id=$sourceId) AND ($targetId IS NULL OR target.id=$targetId) AND ALL(rel IN rels WHERE type(rel) IN $types) RETURN [n IN nodes(path) | n{.*, properties: properties(n)}] AS nodes, [r IN relationships(path) | r{.*, source: startNode(r).id, target: endNode(r).id, relationshipType: type(r), properties: properties(r)}] AS relationships LIMIT $limit`;const result=await this.neo4j.read(query,{sourceId:request.sourceNodeId??null,targetId:request.targetNodeId??null,types:this.allowed(request.allowedRelationshipTypes),limit});const nodes=new Map<string,any>(),relationships=new Map<string,any>();result.records.forEach((record:any)=>{(record.get('nodes')??[]).forEach((node:any)=>nodes.set(node.id,node));(record.get('relationships')??[]).forEach((rel:any)=>relationships.set(rel.id,rel))});return{nodes:[...nodes.values()],relationships:[...relationships.values()]}}
  allowed(requested?:string[]){return(requested?.length?requested:ALLOWED_RELATIONSHIPS).filter(type=>ALLOWED_RELATIONSHIPS.includes(type))}
}
