import { useState } from 'react'
import type { GraphLayout } from '../../types/graph'
import { loadSavedViews, saveSavedViews, type GraphClusterMode, type GraphViewMode, type SavedGraphView } from '../../services/graphPresentation'

const views: [GraphViewMode,string][] = [['overview','Overview'],['identity','Identity'],['access','Access'],['infrastructure','Infrastructure'],['business','Business Services'],['privileged','Privileged Paths'],['full','Full Graph']]
const clusters: [GraphClusterMode,string][] = [['none','No clustering'],['nodeType','Node type'],['department','Department'],['sourceSystem','Source system'],['domain','Domain'],['environment','Environment'],['application','Application / service']]
const layouts: [GraphLayout,string][] = [['force','Force'],['hierarchy-lr','Hierarchy L→R'],['hierarchy-td','Hierarchy T→B'],['radial','Radial'],['concentric','Concentric'],['department','Department clusters'],['source','Source-system clusters']]

export function GraphWorkspaceControls({ viewMode, clustering, layout, snapshot, onViewMode, onClustering, onLayout, onLoad }: { viewMode: GraphViewMode; clustering: GraphClusterMode; layout: GraphLayout; snapshot: Omit<SavedGraphView,'id'|'name'>; onViewMode: (value: GraphViewMode)=>void; onClustering:(value:GraphClusterMode)=>void; onLayout:(value:GraphLayout)=>void; onLoad:(view:SavedGraphView)=>void }) {
  const [saved,setSaved]=useState(()=>typeof localStorage==='undefined'?[]:loadSavedViews(localStorage))
  const persist=(next:SavedGraphView[])=>{setSaved(next);if(typeof localStorage!=='undefined')saveSavedViews(localStorage,next)}
  const create=()=>{const name=window.prompt('Saved view name',`Graph view ${saved.length+1}`)?.trim();if(name)persist([...saved,{...snapshot,id:crypto.randomUUID(),name}])}
  const rename=(view:SavedGraphView)=>{const name=window.prompt('Rename saved view',view.name)?.trim();if(name)persist(saved.map((item)=>item.id===view.id?{...item,name}:item))}
  return <div className="mt-4 space-y-3 rounded-lg border border-border bg-card/40 p-3">
    <label className="block text-[10px] font-semibold uppercase tracking-wider text-gray-500">View mode<select aria-label="Graph view mode" value={viewMode} onChange={(e)=>onViewMode(e.target.value as GraphViewMode)} className="mt-1 w-full rounded border border-border bg-surface px-2 py-1.5 text-xs text-gray-200">{views.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label className="block text-[10px] font-semibold uppercase tracking-wider text-gray-500">Visual clustering<select aria-label="Visual clustering" value={clustering} onChange={(e)=>onClustering(e.target.value as GraphClusterMode)} className="mt-1 w-full rounded border border-border bg-surface px-2 py-1.5 text-xs text-gray-200">{clusters.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label className="block text-[10px] font-semibold uppercase tracking-wider text-gray-500">Layout<select aria-label="Graph layout" value={layout} onChange={(e)=>onLayout(e.target.value as GraphLayout)} className="mt-1 w-full rounded border border-border bg-surface px-2 py-1.5 text-xs text-gray-200">{layouts.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <div className="border-t border-border pt-2"><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-wider text-gray-500">Saved views</span><button onClick={create} className="rounded border border-border px-2 py-1 text-[10px] text-primary hover:bg-primary/10">Save</button></div>{saved.length===0?<p className="text-[10px] text-gray-600">Save this workspace configuration for later.</p>:<div className="space-y-1">{saved.map((view)=><div key={view.id} className="flex items-center gap-1 rounded bg-surface/60 p-1"><button className="min-w-0 flex-1 truncate text-left text-[10px] text-gray-300 hover:text-white" onClick={()=>onLoad(view)}>{view.name}</button><button aria-label={`Rename ${view.name}`} title="Rename" onClick={()=>rename(view)} className="px-1 text-gray-500 hover:text-white">✎</button><button aria-label={`Delete ${view.name}`} title="Delete" onClick={()=>persist(saved.filter((item)=>item.id!==view.id))} className="px-1 text-gray-500 hover:text-danger">×</button></div>)}</div>}</div>
  </div>
}
