import{FindingCategory as C,FindingSeverity as S,type RiskRule}from'../risk.types';import{isUser,match,outgoing,p,text}from'./helpers'
const access=(g:any,n:any,predicate:(x:any)=>boolean)=>outgoing(g,n.id,['HAS_ACCESS','HAS_ACCESS_TO','AUTHENTICATES_TO','USES']).filter((r:any)=>predicate(g.nodes.find((x:any)=>x.id===r.target)))
export const accessRules:RiskRule[]=[
{id:'production-host-access',title:'User with production host access',category:C.INFRASTRUCTURE,defaultSeverity:S.MEDIUM,remediation:'Validate business need and enforce least privilege.',detect:g=>g.nodes.filter(isUser).flatMap(n=>access(g,n,t=>['HOST','COMPUTER'].includes(t?.nodeType)&&text(p(t,'environment'))==='production').map((r:any)=>match([n.id,r.target],[r.id])))},
{id:'finance-application-access',title:'User with finance application access',category:C.DATA_EXPOSURE,defaultSeverity:S.HIGH,remediation:'Recertify finance application access and enforce conditional controls.',detect:g=>g.nodes.filter(isUser).flatMap(n=>access(g,n,t=>t?.nodeType==='APPLICATION'&&(text(t.displayName).includes('finance')||text(p(t,'department')).includes('finance'))).map((r:any)=>match([n.id,r.target],[r.id])))},
{id:'unrestricted-sudo',title:'Unrestricted sudo rule',category:C.CONFIGURATION,defaultSeverity:S.CRITICAL,remediation:'Replace unrestricted sudo with command-scoped policy.',detect:g=>g.nodes.filter(n=>n.nodeType==='SUDO_POLICY'&&(p(n,'unrestricted')===true||text(p(n,'commands'))==='all'||text(p(n,'rule')).includes('all=(all)'))).map(n=>match([n.id]))},
{id:'ssh-key-privileged-identity',title:'SSH key on privileged identity',category:C.ACCESS,defaultSeverity:S.HIGH,remediation:'Rotate the key, verify ownership, and restrict privileged SSH access.',detect:g=>g.relationships.filter(r=>r.relationshipType==='HAS_SSH_KEY').filter(r=>{const n=g.nodes.find(x=>x.id===r.source);return n&&p(n,'privileged')===true}).map(r=>match([r.source,r.target],[r.id]))},
{id:'cross-domain-privileged-reachability',title:'Cross-domain privileged reachability',category:C.LATERAL_MOVEMENT,defaultSeverity:S.CRITICAL,remediation:'Review cross-domain trusts and isolate privileged administration paths.',detect:g=>g.relationships.filter(r=>['TRUSTS','HAS_ACCESS','HAS_ACCESS_TO','MEMBER_OF'].includes(r.relationshipType)).filter(r=>{const a=g.nodes.find(n=>n.id===r.source),b=g.nodes.find(n=>n.id===r.target);return a&&b&&p(a,'domain')&&p(b,'domain')&&p(a,'domain')!==p(b,'domain')&&(p(a,'privileged')||p(b,'privileged'))}).map(r=>match([r.source,r.target],[r.id]))},
]
