import{FindingCategory as C,FindingSeverity as S,type RiskRule}from'../risk.types';import{isUser,match,outgoing,p,pathTo,privileged,text}from'./helpers'
const admin=(n:any)=>text(n?.displayName).includes('domain admin')||text(p(n,'role')).includes('domain admin')
export const privilegeRules:RiskRule[]=[
{id:'direct-domain-admin',title:'Direct Domain Admin membership',category:C.PRIVILEGE,defaultSeverity:S.CRITICAL,remediation:'Use time-bound privileged access and remove direct membership.',detect:g=>g.relationships.filter(r=>r.relationshipType==='MEMBER_OF').filter(r=>admin(g.nodes.find(n=>n.id===r.target))).map(r=>match([r.source,r.target],[r.id],{},[r.source,r.target]))},
{id:'inherited-domain-admin',title:'Inherited Domain Admin reachability',category:C.PRIVILEGE,defaultSeverity:S.HIGH,remediation:'Break nested privilege inheritance and use dedicated administrative groups.',detect:(g,d)=>g.nodes.filter(isUser).flatMap(n=>{const path=pathTo(g,n.id,admin,d);return path&&path.length>2?[match(path,[],{},path)]:[]})},
{id:'privileged-service-account',title:'Privileged service account',category:C.PRIVILEGE,defaultSeverity:S.HIGH,remediation:'Minimize privileges and rotate managed credentials.',detect:g=>g.nodes.filter(n=>['SERVICE_ACCOUNT','MANAGED_SERVICE_ACCOUNT'].includes(n.nodeType)&&privileged(n)).map(n=>match([n.id]))},
{id:'high-risk-service-account',title:'High-risk service account',category:C.ACCOUNT,defaultSeverity:S.HIGH,remediation:'Review service ownership, activity, credentials, and entitlements.',detect:g=>g.nodes.filter(n=>['SERVICE_ACCOUNT','MANAGED_SERVICE_ACCOUNT'].includes(n.nodeType)&&['HIGH','CRITICAL'].includes(n.riskLevel??'')).map(n=>match([n.id]))},
{id:'nested-privileged-group',title:'Nested privileged group membership',category:C.PRIVILEGE,defaultSeverity:S.HIGH,remediation:'Flatten or tightly govern nested privileged group membership.',detect:g=>g.relationships.filter(r=>r.relationshipType==='MEMBER_OF').filter(r=>{const a=g.nodes.find(n=>n.id===r.source),b=g.nodes.find(n=>n.id===r.target);return a?.nodeType.includes('GROUP')&&b?.nodeType.includes('GROUP')&&privileged(b)}).map(r=>match([r.source,r.target],[r.id]))},
]
