import type { BusinessQuestion, QuestionCategory } from '../types/businessQuestions'

export const questionCatalog: BusinessQuestion[] = [
  {
    id: 'who-access-host',
    title: 'Who can access this host?',
    description: 'List all users and identities that can authenticate to or access this host.',
    category: 'Access',
    icon: 'Server',
    resultType: 'node',
    requiresInput: true,
    inputLabel: 'Select a host',
    inputPlaceholder: 'Search hosts...',
    inputType: 'host',
  },
  {
    id: 'who-access-app',
    title: 'Who has access to this application?',
    description: 'Find all users with permissions to a specific application through group/role membership.',
    category: 'Access',
    icon: 'AppWindow',
    resultType: 'path',
    requiresInput: true,
    inputLabel: 'Select an application',
    inputPlaceholder: 'Search applications...',
    inputType: 'application',
  },
  {
    id: 'domain-admins',
    title: 'Which users are Domain Admins?',
    description: 'List all users who are direct members of the Domain Admins group.',
    category: 'Identity',
    icon: 'Shield',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'inherit-domain-admin',
    title: 'Which users inherit Domain Admin?',
    description: 'Find all users who inherit Domain Admin through nested group membership.',
    category: 'Identity',
    icon: 'GitBranch',
    resultType: 'path',
    requiresInput: false,
  },
  {
    id: 'production-access',
    title: 'Which users have Production access?',
    description: 'Identify users with access to production hosts and applications.',
    category: 'Access',
    icon: 'Activity',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'finance-app-access',
    title: 'Which users have Finance application access?',
    description: 'Find users who can access financial applications like the Payment Gateway.',
    category: 'Access',
    icon: 'Wallet',
    resultType: 'path',
    requiresInput: false,
  },
  {
    id: 'sudo-users',
    title: 'Which users have sudo?',
    description: 'List all Linux users with sudo privileges on any host.',
    category: 'Linux',
    icon: 'Shield',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'sudo-groups',
    title: 'Which Linux groups grant sudo?',
    description: 'Show Linux groups whose membership grants sudo access.',
    category: 'Linux',
    icon: 'Users',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'privileged-service-accounts',
    title: 'Which service accounts are privileged?',
    description: 'Identify service accounts with elevated privileges or broad access.',
    category: 'Privilege',
    icon: 'Bot',
    resultType: 'risk',
    requiresInput: false,
  },
  {
    id: 'ssh-users',
    title: 'Which users have SSH access?',
    description: 'List users with registered SSH keys for Linux access.',
    category: 'Linux',
    icon: 'Key',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'orphan-groups',
    title: 'Which orphan groups exist?',
    description: 'Find groups with no direct members that can be cleaned up.',
    category: 'Identity',
    icon: 'UserX',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'disabled-users-access',
    title: 'Which disabled users still have access?',
    description: 'Identify disabled user accounts that still have active group/role assignments.',
    category: 'Risk',
    icon: 'AlertTriangle',
    resultType: 'risk',
    requiresInput: false,
  },
  {
    id: 'cross-system-accounts',
    title: 'Which accounts exist in multiple systems?',
    description: 'Find identities that are linked across Active Directory, FreeIPA, and Linux.',
    category: 'Identity',
    icon: 'GitMerge',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'highest-risk-identities',
    title: 'Which identities have the highest risk?',
    description: 'List identities sorted by risk level (Critical, High, Medium).',
    category: 'Risk',
    icon: 'Skull',
    resultType: 'risk',
    requiresInput: false,
  },
  {
    id: 'bsvc-depend-on-host',
    title: 'Which business services depend on this host?',
    description: 'Show business services that would be affected if this host becomes unavailable.',
    category: 'Business Impact',
    icon: 'Building2',
    resultType: 'tree',
    requiresInput: true,
    inputLabel: 'Select a host',
    inputPlaceholder: 'Search hosts...',
    inputType: 'host',
  },
  {
    id: 'host-compromise-impact',
    title: 'If this host is compromised, what is affected?',
    description: 'Analyze blast radius: show applications, databases, and business services on this host.',
    category: 'Business Impact',
    icon: 'Skull',
    resultType: 'tree',
    requiresInput: true,
    inputLabel: 'Select a host',
    inputPlaceholder: 'Search hosts...',
    inputType: 'host',
  },
  {
    id: 'group-removal-impact',
    title: 'If this group is removed, what breaks?',
    description: 'Analyze impact: list affected users, permissions, and applications tied to this group.',
    category: 'Business Impact',
    icon: 'Users',
    resultType: 'tree',
    requiresInput: true,
    inputLabel: 'Select a group',
    inputPlaceholder: 'Search groups...',
    inputType: 'group',
  },
  {
    id: 'app-removal-user-impact',
    title: 'If this application is removed, what users lose access?',
    description: 'Find all users that would lose access to this application through their current permissions.',
    category: 'Business Impact',
    icon: 'AppWindow',
    resultType: 'path',
    requiresInput: true,
    inputLabel: 'Select an application',
    inputPlaceholder: 'Search applications...',
    inputType: 'application',
  },
  {
    id: 'nested-group-membership',
    title: 'Which groups have nested membership?',
    description: 'Find groups that contain other groups as members, creating inheritance chains.',
    category: 'Identity',
    icon: 'GitBranch',
    resultType: 'path',
    requiresInput: false,
  },
  {
    id: 'direct-privilege-roles',
    title: 'Which roles grant direct privileges?',
    description: 'List roles and the permissions they grant to applications.',
    category: 'Privilege',
    icon: 'Key',
    resultType: 'table',
    requiresInput: false,
  },
  {
    id: 'ad-users-linux-access',
    title: 'Which AD users have Linux access?',
    description: 'Find Active Directory users that can reach Linux hosts through identity mapping.',
    category: 'Linux',
    icon: 'Monitor',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'hosts-no-apps',
    title: 'Which hosts have no applications?',
    description: 'Identify hosts that are not running any known applications.',
    category: 'Infrastructure',
    icon: 'Server',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'users-in-multiple-groups',
    title: 'Which users belong to the most groups?',
    description: 'Find users with the most group memberships as risk indicators.',
    category: 'Identity',
    icon: 'Users',
    resultType: 'table',
    requiresInput: false,
  },
  {
    id: 'critical-applications',
    title: 'Which applications are business-critical?',
    description: 'Show applications that support critical business services.',
    category: 'Infrastructure',
    icon: 'Building2',
    resultType: 'table',
    requiresInput: false,
  },
  {
    id: 'sudo-wildcard-rules',
    title: 'Which sudo rules are wildcard?',
    description: 'Identify sudo policies that grant ALL commands (security risk).',
    category: 'Risk',
    icon: 'Shield',
    resultType: 'risk',
    requiresInput: false,
  },
  {
    id: 'privileged-group-members',
    title: 'Which users are in privileged groups?',
    description: 'Find members of admin, enterprise, and sudo groups across systems.',
    category: 'Privilege',
    icon: 'Shield',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'orphan-service-accounts',
    title: 'Which service accounts are orphaned?',
    description: 'Find service accounts not managed by any user or application.',
    category: 'Infrastructure',
    icon: 'Bot',
    resultType: 'node',
    requiresInput: false,
  },
  {
    id: 'app-user-count',
    title: 'How many users per application?',
    description: 'Count unique users with access to each application.',
    category: 'Access',
    icon: 'BarChart3',
    resultType: 'table',
    requiresInput: false,
  },
]

export function getQuestionById(id: string): BusinessQuestion | undefined {
  return questionCatalog.find((q) => q.id === id)
}

export function getQuestionsByCategory(category: QuestionCategory): BusinessQuestion[] {
  return questionCatalog.filter((q) => q.category === category)
}

export function getCategories(): QuestionCategory[] {
  const cats = new Set(questionCatalog.map((q) => q.category))
  return Array.from(cats)
}
