import type { GraphLink, GraphNode } from '../types/graph'
const BASE=((import.meta as any).env?.VITE_API_URL||'/api').replace(/\/$/,'')
export interface ExplorerQuery { q?:string;nodeTypes?:string[];sourceSystems?:string[];riskLevels?:string[];statuses?:string[];types?:string[];limit?:number;offset?:number;sortBy?:string;sortDirection?:'ASC'|'DESC';format?:'json'|'csv' }
export interface ExplorerPage { items:GraphNode[];total:number;limit:number;offset:number;hasMore:boolean;sortBy:string;sortDirection:string }
export interface RelationshipItem { relationship:GraphLink&{properties?:Record<string,unknown>};sourceName:string;targetName:string }
export interface RelationshipPage { items:RelationshipItem[];total:number;limit:number;offset:number;hasMore:boolean }
const params=(input:ExplorerQuery)=>{const out=new URLSearchParams();Object.entries(input).forEach(([key,value])=>{if(Array.isArray(value)){if(value.length)out.set(key,value.join(','))}else if(value!==undefined&&value!=='')out.set(key,String(value))});return out}
async function get<T>(path:string){const response=await fetch(`${BASE}${path}`);if(!response.ok)throw new Error(response.status===400?'Explorer filters are invalid':response.status===503?'Neo4j is unavailable':`Explorer request failed (${response.status})`);return response.json()as Promise<T>}
export const exploreNodes=(input:ExplorerQuery)=>get<ExplorerPage>(`/graph/explorer/nodes?${params(input)}`)
export const exploreRelationships=(input:ExplorerQuery)=>get<RelationshipPage>(`/graph/explorer/relationships?${params(input)}`)
export const explorerExportUrl=(kind:'nodes'|'relationships',format:'json'|'csv',input:ExplorerQuery)=>`${BASE}/graph/explorer/${kind}/export?${params({...input,format})}`
export function exportNodes(items:GraphNode[],format:'json'|'csv'){const content=format==='json'?JSON.stringify(items,null,2):[['id','displayName','nodeType','sourceSystem','riskLevel','status'],...items.map(node=>[node.id,node.displayName,node.nodeType,node.sourceSystem,node.riskLevel,String(node.properties?.status??'')])].map(row=>row.map(value=>`"${String(value).replace(/"/g,'""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([content],{type:format==='json'?'application/json':'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`identity-access-${Date.now()}.${format}`;anchor.click();URL.revokeObjectURL(url)}
