import type { GraphData,GraphFiltersState,GraphLayout,GraphLink,GraphNode,RiskLevel } from '../types/graph';import type{GraphSourceMode}from'../types/neo4j'
export type GraphViewMode='overview'|'identity'|'access'|'infrastructure'|'business'|'privileged'|'full'
export type GraphClusterMode='none'|'nodeType'|'department'|'sourceSystem'|'domain'|'environment'|'application'
const modeTypes:Record<Exclude<GraphViewMode,'overview'|'full'|'privileged'>,Set<string>>={identity:new Set(['USER','LINUX_USER','GROUP','LINUX_GROUP','DEPARTMENT','TEAM','MANAGER','SERVICE_ACCOUNT']),access:new Set(['USER','GROUP','ROLE','PERMISSION','APPLICATION','DATABASE','SSH_KEY','SUDO_POLICY']),infrastructure:new Set(['HOST','COMPUTER','DATABASE','APPLICATION','DOMAIN','FOREST','ORGANIZATIONAL_UNIT']),business:new Set(['BUSINESS_SERVICE','APPLICATION','DATABASE','DEPARTMENT','TEAM'])}
const ids=(link:GraphLink)=>[typeof link.source==='object'?(link.source as any).id:link.source,typeof link.target==='object'?(link.target as any).id:link.target]as const
export function filterGraphView(data:GraphData,mode:GraphViewMode):GraphData{if(mode==='full')return data;let seeds=data.nodes.filter((node)=>{if(mode==='overview')return['CRITICAL','HIGH'].includes(node.riskLevel)||node.properties.privileged===true||['USER','GROUP','ROLE','HOST','APPLICATION','BUSINESS_SERVICE'].includes(node.nodeType);if(mode==='privileged')return node.properties.privileged===true||['ROLE','PERMISSION','SUDO_POLICY','SSH_KEY'].includes(node.nodeType)||['CRITICAL','HIGH'].includes(node.riskLevel);return modeTypes[mode].has(node.nodeType)});if(mode==='overview'&&seeds.length>120)seeds=seeds.sort((a,b)=>riskRank(b.riskLevel)-riskRank(a.riskLevel)).slice(0,120);const visible=new Set(seeds.map((node)=>node.id));data.links.forEach((link)=>{const[source,target]=ids(link);if(visible.has(source)||visible.has(target)){visible.add(source);visible.add(target)}});return{nodes:data.nodes.filter((node)=>visible.has(node.id)),links:data.links.filter((link)=>{const[source,target]=ids(link);return visible.has(source)&&visible.has(target)})}}
function clusterKey(node:GraphNode,mode:GraphClusterMode){if(mode==='nodeType')return node.nodeType;if(mode==='sourceSystem')return node.sourceSystem;if(mode==='department')return String(node.properties.department??'Unassigned');if(mode==='domain')return String(node.properties.domain??'No domain');if(mode==='environment')return String(node.properties.environment??'Unknown environment');return String(node.properties.applicationName??node.properties.businessService??'Unassigned service')}
export function clusterGraph(data:GraphData,mode:GraphClusterMode):GraphData{if(mode==='none')return data;const groups=new Map<string,GraphNode[]>();data.nodes.forEach((node)=>{const key=clusterKey(node,mode);groups.set(key,[...(groups.get(key)??[]),node])});const memberToCluster=new Map<string,string>();const nodes=[...groups].map(([name,members])=>{const id=`cluster:${mode}:${name}`;members.forEach((member)=>memberToCluster.set(member.id,id));const high=members.filter((node)=>['CRITICAL','HIGH'].includes(node.riskLevel)).length;return{id,displayName:name,nodeType:'TEAM',sourceSystem:members[0]?.sourceSystem??'CUSTOM',riskLevel:(members.some((node)=>node.riskLevel==='CRITICAL')?'CRITICAL':members.some((node)=>node.riskLevel==='HIGH')?'HIGH':'NONE')as RiskLevel,properties:{isCluster:true,clusterMode:mode,memberIds:members.map((node)=>node.id),nodeCount:members.length,highRiskCount:high,sourceSystems:[...new Set(members.map((node)=>node.sourceSystem))]}}as GraphNode});const links=new Map<string,GraphLink>();data.links.forEach((link)=>{const[s,t]=ids(link);const source=memberToCluster.get(s)!;const target=memberToCluster.get(t)!;if(source===target)return;const key=`${source}|${link.relationshipType}|${target}`;if(!links.has(key))links.set(key,{...link,id:`cluster-link:${key}`,source,target})});return{nodes,links:[...links.values()]}}
export function riskRank(risk:RiskLevel){return{NONE:0,LOW:1,MEDIUM:2,HIGH:3,CRITICAL:4}[risk]}
export function labelVisibility(node:GraphNode,zoom:number,state:{selected?:boolean;hovered?:boolean;path?:boolean}){const privileged=node.properties.privileged===true;const important=['CRITICAL','HIGH'].includes(node.riskLevel)||privileged||['BUSINESS_SERVICE','ROLE'].includes(node.nodeType);if(zoom<.55)return Boolean(state.selected||state.hovered||state.path||node.riskLevel==='CRITICAL'||privileged);if(zoom<1.15)return Boolean(state.selected||state.hovered||state.path||important);return true}
export function nodeCollisionRadius(node:GraphNode){const base=['BUSINESS_SERVICE','HOST','COMPUTER','APPLICATION','DATABASE'].includes(node.nodeType)?38:30;return Math.min(64,base+Math.max(0,node.displayName.length-12)*.7)}
export function nodeVisualStyle(node:GraphNode){return{shape:['USER','LINUX_USER'].includes(node.nodeType)?'circle':['GROUP','LINUX_GROUP'].includes(node.nodeType)?'hexagon':node.nodeType==='ROLE'?'shield':node.nodeType==='PERMISSION'?'diamond':node.nodeType==='DATABASE'?'cylinder':['HOST','COMPUTER','APPLICATION'].includes(node.nodeType)?'rectangle':'container',riskRing:{CRITICAL:'pulse-red',HIGH:'orange',MEDIUM:'amber',LOW:'green',NONE:'neutral'}[node.riskLevel],badges:[node.sourceSystem,node.properties.status,node.properties.privileged===true?'PRIV':null,node.properties.correlationConfidence?'CORR':null].filter(Boolean)}}
export function edgeVisualStyle(link:GraphLink,state:{selected?:boolean;shortest?:boolean;attack?:boolean;upstream?:boolean;downstream?:boolean}){const inherited=['MEMBER_OF','BELONGS_TO','APPLIES_TO'].includes(link.relationshipType);const stale=(link as any).properties?.status==='STALE'||(link as any).properties?.status==='DISABLED';return{color:state.attack?'attack':state.shortest||state.selected?'cyan':state.upstream?'red':state.downstream?'green':['HAS_ROLE','GRANTS','HAS_PERMISSION'].includes(link.relationshipType)?'orange':'neutral',dash:stale?'dotted':inherited?'dashed':'solid',opacity:stale ? .35 : 1}}
export function disconnectedComponentPositions(data:GraphData){const adjacent=new Map(data.nodes.map((node)=>[node.id,[]as string[]]));data.links.forEach((link)=>{const[a,b]=ids(link);adjacent.get(a)?.push(b);adjacent.get(b)?.push(a)});const seen=new Set<string>();const result=new Map<string,{x:number;y:number}>();let component=0;for(const node of data.nodes){if(seen.has(node.id))continue;const queue=[node.id];const members:string[]=[];seen.add(node.id);while(queue.length){const id=queue.shift()!;members.push(id);adjacent.get(id)?.forEach((next)=>{if(!seen.has(next)){seen.add(next);queue.push(next)}})}const ring=Math.ceil(Math.sqrt(component));const angle=component*2.399;const ox=component?Math.cos(angle)*(170+ring*130):0;const oy=component?Math.sin(angle)*(170+ring*130):0;members.forEach((id,index)=>result.set(id,{x:ox+Math.cos(index*2.399)*Math.sqrt(index)*24,y:oy+Math.sin(index*2.399)*Math.sqrt(index)*24}));component++}return result}
export interface SavedGraphView{id:string;name:string;layout:GraphLayout;filters:GraphFiltersState;source:GraphSourceMode;focusedNode?:string;expandedNodes:string[];clustering:GraphClusterMode;viewMode:GraphViewMode}
const SAVED_KEY='iag-saved-graph-views';export function loadSavedViews(storage:Pick<Storage,'getItem'>):SavedGraphView[]{try{const value=JSON.parse(storage.getItem(SAVED_KEY)??'[]');return Array.isArray(value)?value:[]}catch{return[]}}export function saveSavedViews(storage:Pick<Storage,'setItem'>,views:SavedGraphView[]){storage.setItem(SAVED_KEY,JSON.stringify(views))}
export function layoutKey(source:GraphSourceMode){return`iag-graph-layout:${source}`}export function loadLayout(storage:Pick<Storage,'getItem'>,source:GraphSourceMode):GraphLayout{return(storage.getItem(layoutKey(source))as GraphLayout)||'force'}export function saveLayout(storage:Pick<Storage,'setItem'>,source:GraphSourceMode,layout:GraphLayout){storage.setItem(layoutKey(source),layout)}
