import type { GraphNode, NodeType, RiskLevel, SourceSystem } from '../types/graph'

export const APP_ROUTES = ['/', '/graph', '/pipeline', '/linux-admin', '/business-questions', '/imports', '/identities', '/groups', '/access', '/settings', '/risk'] as const
export const KPI_ROUTES: Record<string, string> = { 'Total Identities':'/identities','Active Accounts':'/identities?status=ACTIVE','Disabled Accounts':'/identities?status=DISABLED','Privileged Accounts':'/identities?privileged=true','Applications':'/graph?nodeType=APPLICATION','Hosts':'/graph?nodeType=HOST','Databases':'/graph?nodeType=DATABASE','Business Services':'/graph?nodeType=BUSINESS_SERVICE','Critical Risks':'/graph?risk=CRITICAL','Open Findings':'/risk' }
export const QUICK_ACTION_ROUTES: Record<string, string> = { 'Import Data':'/imports','Open Graph':'/graph','Business Questions':'/business-questions','Identity Search':'/identities','Run Correlation':'/imports?step=correlation','Investigate':'/graph?mode=investigation','Open Pipeline':'/pipeline' }
export function isKnownRoute(pathname: string) { return APP_ROUTES.some((route) => route === pathname) || /^\/identities\/[^/]+$/.test(pathname) }
export type GraphQuery = { nodeId?: string; nodeType?: NodeType; sourceSystem?: SourceSystem; risk?: RiskLevel; status?: string; mode?: string; importId?: string }
export function parseGraphQuery(params: URLSearchParams): GraphQuery { return Object.fromEntries(['nodeId','nodeType','sourceSystem','risk','status','mode','importId'].flatMap((key) => params.get(key) ? [[key, params.get(key)!]] : [])) as GraphQuery }
export function filterIdentities(nodes: GraphNode[], params: URLSearchParams, search = '') { const status = params.get('status'); const privileged = params.get('privileged'); const source = params.get('sourceSystem'); const department = params.get('department'); const risk = params.get('risk'); const query = search.toLowerCase(); return nodes.filter((node) => ['USER','LINUX_USER','SERVICE_ACCOUNT','MANAGED_SERVICE_ACCOUNT'].includes(node.nodeType)).filter((node) => !status || String(node.properties.status ?? 'ACTIVE').toUpperCase() === status.toUpperCase()).filter((node) => privileged !== 'true' || node.properties.privileged === true || node.riskLevel === 'CRITICAL' || node.riskLevel === 'HIGH').filter((node) => !source || node.sourceSystem === source).filter((node) => !department || String(node.properties.department ?? '').toLowerCase() === department.toLowerCase()).filter((node) => !risk || node.riskLevel === risk).filter((node) => !query || `${node.displayName} ${node.properties.username ?? ''} ${node.properties.email ?? ''}`.toLowerCase().includes(query)) }
export function searchNavigationNodes(nodes: GraphNode[], query: string) { const searchable = new Set(['USER','LINUX_USER','GROUP','LINUX_GROUP','HOST','COMPUTER','APPLICATION','DATABASE','BUSINESS_SERVICE']); const term = query.trim().toLowerCase(); return term ? nodes.filter((node) => searchable.has(node.nodeType) && `${node.displayName} ${node.id} ${node.properties.username ?? ''} ${node.properties.email ?? ''} ${node.properties.employeeId ?? ''}`.toLowerCase().includes(term)).slice(0, 8) : [] }
export function nodeDestination(node: GraphNode) { if (node.nodeType === 'USER' || node.nodeType === 'LINUX_USER') return `/identities/${encodeURIComponent(node.id)}`; if ((node.nodeType === 'HOST' || node.nodeType === 'COMPUTER') && node.sourceSystem === 'LINUX') return `/linux-admin?hostId=${encodeURIComponent(node.id)}`; return `/graph?nodeId=${encodeURIComponent(node.id)}` }
export type FrontendSettings = { graphSource: 'mock' | 'imported' | 'neo4j'; layout: 'force' | 'hierarchy' | 'radial' | 'concentric'; showLabels: boolean; animations: boolean; compact: boolean; pageSize: number; neo4jNodeLimit:number; neo4jRelationshipLimit:number; autoFallback:boolean; apiTimeoutMs:number }
export const DEFAULT_SETTINGS: FrontendSettings = { graphSource: 'mock', layout: 'force', showLabels: true, animations: true, compact: false, pageSize: 25, neo4jNodeLimit:300, neo4jRelationshipLimit:1200, autoFallback:false, apiTimeoutMs:10000 }
export function loadSettings(storage: Pick<Storage, 'getItem'>): FrontendSettings { try { return { ...DEFAULT_SETTINGS, ...JSON.parse(storage.getItem('iag-settings') ?? '{}') } } catch { return DEFAULT_SETTINGS } }
export function saveSettings(storage: Pick<Storage, 'setItem'>, settings: FrontendSettings) { storage.setItem('iag-settings', JSON.stringify(settings)) }
