import type { BackendGraphNode,BackendSubgraph,DashboardSummary,GraphStatsResponse,Neo4jHealth } from '../types/neo4j'
const API_BASE=((import.meta as any).env?.VITE_API_URL||'').replace(/\/$/,'')
export class Neo4jApiError extends Error{constructor(message:string,readonly status?:number,readonly code?:'TIMEOUT'|'ABORTED'|'UNAVAILABLE'|'INVALID_RESPONSE'){super(message);this.name='Neo4jApiError'}}
export interface RequestOptions{signal?:AbortSignal;timeoutMs?:number}
async function request<T>(path:string,options:RequestOptions={}):Promise<T>{const controller=new AbortController();let timedOut=false;const timeout=globalThis.setTimeout(()=>{timedOut=true;controller.abort()},options.timeoutMs??10000);const abort=()=>controller.abort();options.signal?.addEventListener('abort',abort,{once:true});try{const response=await fetch(`${API_BASE}${path}`,{signal:controller.signal});if(!response.ok){let message=response.status===503?'Neo4j is disabled or unavailable':`Graph API request failed (${response.status})`;try{const body=await response.json();if(typeof body?.message==='string'&&!body.message.includes(' at '))message=body.message}catch{}throw new Neo4jApiError(message,response.status,response.status===503?'UNAVAILABLE':undefined)}const value=await response.json();if(value===null||typeof value!=='object')throw new Neo4jApiError('Invalid graph API response',response.status,'INVALID_RESPONSE');return value as T}catch(error){if(error instanceof Neo4jApiError)throw error;if((error as Error).name==='AbortError')throw new Neo4jApiError(timedOut?'Graph request timed out':'Graph request cancelled',undefined,timedOut?'TIMEOUT':'ABORTED');throw new Neo4jApiError('Unable to reach the graph service',undefined,'UNAVAILABLE')}finally{globalThis.clearTimeout(timeout);options.signal?.removeEventListener('abort',abort)}}
function query(path:string,values:Record<string,unknown>){const params=new URLSearchParams();Object.entries(values).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=='')params.set(key,String(value))});return`${path}${params.size?`?${params}`:''}`}
export const getHealth=(options?:RequestOptions)=>request<Neo4jHealth>('/health/neo4j',options)
export const searchNodes=(search:string,filters:Record<string,unknown>={},options?:RequestOptions)=>request<BackendGraphNode[]>(query('/graph/search',{q:search,...filters}),options)
export const getNode=(id:string,options?:RequestOptions)=>request<BackendGraphNode>(`/graph/nodes/${encodeURIComponent(id)}`,options)
export const getNeighbors=(id:string,values:Record<string,unknown>={},options?:RequestOptions)=>request<BackendSubgraph>(query(`/graph/nodes/${encodeURIComponent(id)}/neighbors`,values),options)
export const getSubgraph=(values:Record<string,unknown>={},options?:RequestOptions)=>request<BackendSubgraph>(query('/graph/subgraph',values),options)
export const getDashboardSummary=(filters:Record<string,unknown>={},options?:RequestOptions)=>request<DashboardSummary>(query('/graph/dashboard-summary',filters),options)
export const getGraphStats=(options?:RequestOptions)=>request<GraphStatsResponse>('/graph/stats',options)
