import assert from'node:assert/strict';import{describe,it}from'node:test';import{AttackPathRepository}from'../attack-path.repository';import{AttackPathService}from'../attack-path.service';import{PrivilegeTargetService}from'../privilege-target.service';import{PathScoringService}from'../path-scoring.service';import{PathExplanationService}from'../path-explanation.service';import type{GraphSnapshot}from'../../risk'
const node=(id:string,nodeType='USER',properties:Record<string,unknown>={},riskLevel='NONE',sourceSystem='ACTIVE_DIRECTORY')=>({id,displayName:id,nodeType,properties,riskLevel,sourceSystem});const rel=(id:string,source:string,target:string,type='MEMBER_OF')=>({id,source,target,relationshipType:type,sourceSystem:'ACTIVE_DIRECTORY',properties:{}});const graph:GraphSnapshot={nodes:[node('user','USER',{status:'DISABLED',domain:'a'}),node('dev','GROUP',{domain:'a'}),node('admin','GROUP',{isDomainAdmin:true,privileged:true,domain:'b'},'CRITICAL'),node('sudo','SUDO_POLICY',{unrestricted:true,commands:'ALL'}),node('root','LINUX_USER',{rootAccess:true})],relationships:[rel('r1','user','dev'),rel('r2','dev','admin'),rel('cycle','dev','user'),rel('sudo-r','user','sudo','HAS_SUDO_POLICY'),rel('root-r','sudo','root','GRANTS')]}
function service(snapshot=graph){const source={load:async()=>snapshot};const repository=new AttackPathRepository({isEnabled:()=>false}as any,source as any);const risk={list:()=>[],scan:async()=>({})};return{service:new AttackPathService(repository,new PrivilegeTargetService(),new PathScoringService(),new PathExplanationService(),risk as any),repository}}
describe('attack path engine',()=>{
 it('finds the shortest directed Domain Admin path',async()=>{const result=await service().service.search({sourceNodeId:'user',targetNodeId:'admin',maxDepth:5});assert.equal(result.paths[0].totalDepth,2);assert.deepEqual(result.paths[0].nodes.map(n=>n.id),['user','dev','admin'])})
 it('prevents cycles and deduplicates paths',async()=>{const result=await service().service.search({sourceNodeId:'user',targetNodeId:'admin',maxDepth:12,maxPaths:20});assert.equal(new Set(result.paths.map(p=>p.id)).size,result.paths.length);assert.ok(result.paths.every(p=>new Set(p.nodes.map(n=>n.id)).size===p.nodes.length))})
 it('enforces maximum depth and result limits',async()=>{assert.equal((await service().service.search({sourceNodeId:'user',targetNodeId:'admin',maxDepth:1})).count,0);assert.ok((await service().service.search({sourceNodeId:'user',maxPaths:1})).count<=1)})
 it('detects privileged targets using metadata',()=>{const targets=new PrivilegeTargetService().targets(graph);assert.equal(targets.find(t=>t.node.id==='admin')?.type,'DOMAIN_ADMIN');assert.equal(targets.find(t=>t.node.id==='sudo')?.type,'SUDO_ROOT')})
 it('finds sudo/root and cross-domain paths',async()=>{const sudo=await service().service.search({sourceNodeId:'user',targetNodeId:'sudo'});assert.equal(sudo.paths[0].privilegedTargetType,'SUDO_ROOT');const admin=await service().service.search({sourceNodeId:'user',targetNodeId:'admin'});assert.equal(admin.paths[0].type,'CROSS_DOMAIN')})
 it('scores disabled account participation and risky paths',async()=>{const result=await service().service.search({sourceNodeId:'user',targetNodeId:'admin',weighted:true});assert.ok(result.paths[0].factorScores.some(f=>f.factor==='accountState'));assert.ok(result.paths[0].totalRiskScore>=65)})
 it('generates deterministic per-hop explanations',async()=>{const a=(await service().service.search({sourceNodeId:'user',targetNodeId:'admin'})).paths[0];const b=(await service().service.search({sourceNodeId:'user',targetNodeId:'admin'})).paths[0];assert.equal(a.explanation,b.explanation);assert.match(a.explanation,/MEMBER_OF/);assert.equal(a.evidence.length,2)})
 it('uses the disabled Neo4j memory fallback',async()=>{let mode='';const source={load:async(next:string)=>{mode=next;return graph}};const repository=new AttackPathRepository({isEnabled:()=>false}as any,source as any);await repository.graph({graphSource:'auto'});assert.equal(mode,'memory')})
 it('summarizes completed analyses',async()=>{const built=service();await built.service.search({sourceNodeId:'user',maxPaths:10});const summary=built.service.summary();assert.ok(summary.totalPaths>0);assert.equal(summary.uniqueSourceIdentities,1)})
 it('enforces timeout protection',async()=>{const built=service();const original=Date.now;let time=0;Date.now=()=>time+=20;try{await assert.rejects(()=>built.service.search({sourceNodeId:'user',timeoutMs:10}),/timed out/)}finally{Date.now=original}})
})
