import { Injectable } from '@nestjs/common'
import type { Record as Neo4jRecord } from 'neo4j-driver'
import { Neo4jService } from '../../neo4j'
import { GraphRepository } from './graph.repository'
import type { BatchWriteSummary, NeighborOptions, PersistedGraphNode, PersistedGraphRelationship, SearchOptions, SubgraphOptions } from './graph-repository.types'
const NODE_RETURN = 'n{.*, properties: properties(n)} AS node'; const REL_RETURN = 'r{.*, source: startNode(r).id, target: endNode(r).id, properties: properties(r)} AS relationship'
function safeType(type: string) { if (!/^[A-Z][A-Z0-9_]*$/.test(type)) throw new Error('Invalid relationship type'); return type }
function properties(value: Record<string, unknown> = {}) { return Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined).map(([key, item]) => [key, item !== null && typeof item === 'object' && !Array.isArray(item) ? JSON.stringify(item) : item])) }
function nodeRow(node: PersistedGraphNode) { return { id: node.id, properties: properties({ ...node.properties, id: node.id, displayName: node.displayName, nodeType: node.nodeType, sourceSystem: node.sourceSystem, sourceId: node.sourceId, riskLevel: node.riskLevel ?? 'NONE' }) } }
function relRow(rel: PersistedGraphRelationship) { return { id: rel.id, source: rel.source, target: rel.target, sourceSystem: rel.sourceSystem, properties: properties({ ...rel.properties, id: rel.id, sourceSystem: rel.sourceSystem, relationshipType: rel.relationshipType }) } }
function value<T>(record: Neo4jRecord, key: string): T { return record.get(key) as T }
@Injectable()
export class Neo4jGraphRepository extends GraphRepository {
  constructor(private readonly neo4j: Neo4jService) { super() }
  async upsertNode(node: PersistedGraphNode): Promise<PersistedGraphNode> { const result = await this.neo4j.write('MERGE (n:GraphNode {id: $row.id}) SET n += $row.properties RETURN ' + NODE_RETURN, { row: nodeRow(node) }); return value<PersistedGraphNode>(result.records[0], 'node') }
  async upsertNodes(nodes: PersistedGraphNode[]): Promise<BatchWriteSummary> { if (!nodes.length) return { upserted: 0, skipped: 0 }; const rows = nodes.filter((node) => node.id).map(nodeRow); await this.neo4j.write('UNWIND $rows AS row MERGE (n:GraphNode {id: row.id}) SET n += row.properties', { rows }); return { upserted: rows.length, skipped: nodes.length - rows.length } }
  async upsertRelationship(relationship: PersistedGraphRelationship): Promise<PersistedGraphRelationship> { const type = safeType(relationship.relationshipType); const result = await this.neo4j.write(`MATCH (source:GraphNode {id: $row.source}), (target:GraphNode {id: $row.target}) MERGE (source)-[r:${type} {id: $row.id}]->(target) SET r += $row.properties RETURN ${REL_RETURN}`, { row: relRow(relationship) }); if (!result.records[0]) throw new Error('Relationship endpoints were not found'); return value<PersistedGraphRelationship>(result.records[0], 'relationship') }
  async upsertRelationships(relationships: PersistedGraphRelationship[]): Promise<BatchWriteSummary> { let upserted = 0; const groups = new Map<string, PersistedGraphRelationship[]>(); for (const relationship of relationships) { const type = safeType(relationship.relationshipType); groups.set(type, [...(groups.get(type) ?? []), relationship]) } for (const [type, items] of groups) { const rows = items.map(relRow); const result = await this.neo4j.write(`UNWIND $rows AS row MATCH (source:GraphNode {id: row.source}), (target:GraphNode {id: row.target}) MERGE (source)-[r:${type} {id: row.id}]->(target) SET r += row.properties RETURN count(r) AS count`, { rows }); const count = value<any>(result.records[0], 'count'); upserted += Number(count?.toNumber?.() ?? count ?? 0) } return { upserted, skipped: relationships.length - upserted } }
  async getNodeById(id: string): Promise<PersistedGraphNode | null> { const result = await this.neo4j.read('MATCH (n:GraphNode {id: $id}) WHERE n.deletedVersion IS NULL RETURN ' + NODE_RETURN, { id }); return result.records[0] ? value<PersistedGraphNode>(result.records[0], 'node') : null }
  async getNodesByIds(ids: string[]): Promise<PersistedGraphNode[]> { const result = await this.neo4j.read('MATCH (n:GraphNode) WHERE n.id IN $ids AND n.deletedVersion IS NULL RETURN ' + NODE_RETURN, { ids }); return result.records.map((record) => value<PersistedGraphNode>(record, 'node')) }
  async getNeighbors(id: string, options: NeighborOptions = {}): Promise<{ nodes: PersistedGraphNode[]; relationships: PersistedGraphRelationship[] }> { const limit = Math.min(Math.max(options.limit ?? 100, 1), 1000); const pattern = options.direction === 'incoming' ? '<-[r]-' : options.direction === 'outgoing' ? '-[r]->' : '-[r]-'; const query = `MATCH (n:GraphNode {id: $id})${pattern}(neighbor:GraphNode) WHERE n.deletedVersion IS NULL AND neighbor.deletedVersion IS NULL AND r.deletedVersion IS NULL AND (size($types)=0 OR type(r) IN $types) RETURN neighbor{.*, properties: properties(neighbor)} AS node, ${REL_RETURN} LIMIT $limit`; const result = await this.neo4j.read(query, { id, types: options.relationshipTypes ?? [], limit }); return { nodes: result.records.map((record) => value<PersistedGraphNode>(record, 'node')), relationships: result.records.map((record) => value<PersistedGraphRelationship>(record, 'relationship')) } }
  async searchNodes(query: string, options: SearchOptions = {}): Promise<PersistedGraphNode[]> { const result = await this.neo4j.read(`MATCH (n:GraphNode) WHERE n.deletedVersion IS NULL AND (toLower(n.displayName) CONTAINS toLower($query) OR toLower(coalesce(n.username,'')) CONTAINS toLower($query) OR toLower(coalesce(n.email,'')) CONTAINS toLower($query)) AND (size($nodeTypes)=0 OR n.nodeType IN $nodeTypes) AND (size($sources)=0 OR n.sourceSystem IN $sources) AND (size($risks)=0 OR n.riskLevel IN $risks) RETURN ${NODE_RETURN} ORDER BY n.displayName SKIP $offset LIMIT $limit`, { query, nodeTypes: options.nodeTypes ?? [], sources: options.sourceSystems ?? [], risks: options.riskLevels ?? [], offset: Math.max(options.offset ?? 0, 0), limit: Math.min(Math.max(options.limit ?? 50, 1), 500) }); return result.records.map((record) => value<PersistedGraphNode>(record, 'node')) }
  async getSubgraph(ids: string[], options: SubgraphOptions = {}): Promise<{ nodes: PersistedGraphNode[]; relationships: PersistedGraphRelationship[] }> { const depth = Math.min(Math.max(options.depth ?? 1, 1), 5); const limit = Math.min(Math.max(options.limit ?? 500, 1), 2000); const result = await this.neo4j.read(`MATCH path=(start:GraphNode)-[*0..${depth}]-(neighbor:GraphNode) WHERE start.id IN $ids AND ALL(n IN nodes(path) WHERE n.deletedVersion IS NULL) AND ALL(r IN relationships(path) WHERE r.deletedVersion IS NULL) WITH path LIMIT $limit UNWIND nodes(path) AS n UNWIND relationships(path) AS r RETURN collect(DISTINCT n{.*, properties: properties(n)}) AS nodes, collect(DISTINCT r{.*, source: startNode(r).id, target: endNode(r).id, properties: properties(r)}) AS relationships`, { ids, limit }); return result.records[0] ? { nodes: value<PersistedGraphNode[]>(result.records[0], 'nodes'), relationships: value<PersistedGraphRelationship[]>(result.records[0], 'relationships') } : { nodes: [], relationships: [] } }
  async deleteNode(id: string) { const result = await this.neo4j.write('MATCH (n:GraphNode {id: $id}) WITH n, count(n) AS count DETACH DELETE n RETURN count', { id }); const count = value<any>(result.records[0], 'count'); return Number(count?.toNumber?.() ?? count ?? 0) > 0 }
  async deleteRelationship(id: string) { const result = await this.neo4j.write('MATCH ()-[r {id: $id}]-() WITH r, count(r) AS count DELETE r RETURN count', { id }); const count = value<any>(result.records[0], 'count'); return Number(count?.toNumber?.() ?? count ?? 0) > 0 }
}
